# Generated by Django 5.2.12 on 2026-09-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urban_heat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landsurfacetemperature",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to derive LST (e.g., 'Split-Window Algorithm', 'Single-Channel Algorithm')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landsurfacetemperature",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landsurfacetemperature",
            name="satellite_type",
            field=models.CharField(
                blank=True,
                help_text="Satellite or sensor that captured the thermal imagery (e.g., 'Landsat', 'Sentinel', 'MODIS', etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landsurfacetemperature",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., 'Landsat 8/9', 'Sentinel-3', 'MODIS')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meanradianttemperature",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to derive the values (e.g., 'SOLWEIG', 'field measurement')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meanradianttemperature",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meanradianttemperature",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., 'SOLWEIG model output')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to derive the values (e.g., 'SOLWEIG', 'field measurement')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., 'SOLWEIG model output')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skyviewfactor",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to derive the values (e.g., 'SOLWEIG', 'field measurement')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skyviewfactor",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skyviewfactor",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., 'SOLWEIG model output')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surfaceurbanheatislandintensity",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to compute SUHII (e.g., 'urban-rural LST differential')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surfaceurbanheatislandintensity",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surfaceurbanheatislandintensity",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., derived from LandSurfaceTemperature)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utci",
            name="measurement_method",
            field=models.CharField(
                blank=True,
                help_text="Method used to derive the values (e.g., 'SOLWEIG', 'field measurement')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utci",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utci",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Origin of the raster (e.g., 'SOLWEIG model output')",
                max_length=100,
                null=True,
            ),
        ),
    ]
