# Generated by Django 5.2.12 on 2026-09-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urban_heat", "0002_landsurfacetemperature_measurement_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landsurfacetemperature",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="meanradianttemperature",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skyviewfactor",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surfaceurbanheatislandintensity",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="utci",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
    ]
