# Generated by Django 5.2.12 on 2026-09-21 14:48

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urban_heat", "0003_landsurfacetemperature_cog_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WetBulbGlobeTemperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing Wet Bulb Globe Temperature values in degrees Celsius.",
                        null=True,
                        srid=28992,
                        verbose_name="WBGT Raster",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Time the values are valid for (parsed from the KNMI file name)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Origin of the raster (e.g., 'KNMI Data Platform')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "measurement_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used to derive the values (e.g., 'KNMI WBGT analysis')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the raster in meters",
                        null=True,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wet Bulb Globe Temperature",
                "verbose_name_plural": "Wet Bulb Globe Temperature Measurements",
            },
        ),
    ]
