# Generated by Django 5.2.12 on 2026-09-15 12:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cityName",
                    models.CharField(
                        help_text="Name of the city",
                        max_length=100,
                        verbose_name="City Name",
                    ),
                ),
                (
                    "currentPopulation",
                    models.IntegerField(
                        help_text="Total current population in the city",
                        verbose_name="Current Population",
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(help_text="Area in square kilometers", null=True),
                ),
                (
                    "populationDensity",
                    models.FloatField(
                        help_text="Population density in people per square kilometer",
                        null=True,
                        verbose_name="Population Density",
                    ),
                ),
                ("populationDate", models.DateField(null=True)),
                (
                    "popGrowthRate",
                    models.FloatField(help_text="Growth rate in % per year", null=True),
                ),
                (
                    "urbanizationRate",
                    models.FloatField(
                        help_text="Urbanization rate in % per year", null=True
                    ),
                ),
                (
                    "urban_area",
                    models.FloatField(
                        help_text="Urban area in square kilometers", null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Province",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("ProvinceName", models.CharField(max_length=100)),
                (
                    "currentPopulation",
                    models.IntegerField(
                        help_text="Total current population in the Province",
                        null=True,
                        verbose_name="Current Population",
                    ),
                ),
                (
                    "populationDensity",
                    models.FloatField(
                        help_text="Population density in people per square kilometer",
                        null=True,
                        verbose_name="Population Density",
                    ),
                ),
                (
                    "populationDate",
                    models.DateField(
                        help_text="Date of the population data",
                        null=True,
                        verbose_name="Population Date",
                    ),
                ),
                (
                    "area_km2",
                    models.FloatField(help_text="Area in square kilometers", null=True),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                (
                    "districtName",
                    models.CharField(
                        help_text="Name of the district",
                        max_length=100,
                        verbose_name="District Name",
                    ),
                ),
                (
                    "currentPopulation",
                    models.IntegerField(
                        blank=True,
                        help_text="Current population in the district",
                        null=True,
                    ),
                ),
                ("populationDate", models.DateField(null=True)),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                (
                    "populationDensity",
                    models.FloatField(
                        blank=True,
                        help_text="Population density in people per square kilometer",
                        null=True,
                        verbose_name="Population Density",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                (
                    "neighborhoodName",
                    models.CharField(
                        help_text="Name of the neighborhood",
                        max_length=100,
                        verbose_name="Neighborhood Name",
                    ),
                ),
                (
                    "currentPopulation",
                    models.IntegerField(
                        blank=True,
                        help_text="Current population in the neighborhood",
                        null=True,
                        verbose_name="Current Population",
                    ),
                ),
                ("populationDate", models.DateField(null=True)),
                (
                    "area_km2",
                    models.FloatField(
                        blank=True, help_text="Area in square kilometers", null=True
                    ),
                ),
                (
                    "populationDensity",
                    models.FloatField(
                        blank=True,
                        help_text="Population density in people per square kilometer",
                        null=True,
                        verbose_name="Population Density",
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.district",
                    ),
                ),
            ],
            options={
                "verbose_name": "Neighborhood",
                "verbose_name_plural": "Neighborhoods",
            },
        ),
        migrations.AddField(
            model_name="city",
            name="province",
            field=models.ForeignKey(
                help_text="Province code from administrative.Province",
                on_delete=django.db.models.deletion.CASCADE,
                to="administrative.province",
            ),
        ),
    ]
