# Generated by Django 5.2.12 on 2026-09-21 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationProjection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("prognose", "CBS forecast (median)"),
                            ("low", "Lower bound of the 67% interval"),
                            ("high", "Upper bound of the 67% interval"),
                        ],
                        default="prognose",
                        max_length=10,
                    ),
                ),
                (
                    "population",
                    models.IntegerField(
                        help_text="Projected population on 1 January of the year"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="CBS 85173NED", max_length=100
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="population_projections",
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Population Projection",
                "verbose_name_plural": "Population Projections",
                "ordering": ["city", "scenario", "year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("city", "year", "scenario"),
                        name="unique_population_projection",
                    )
                ],
            },
        ),
    ]
