# Generated by Django 5.2.12 on 2026-09-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0002_population_projection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="currentPopulation",
            field=models.IntegerField(
                help_text="Total current population in the city",
                null=True,
                verbose_name="Current Population",
            ),
        ),
    ]
