# Generated by Django 5.2.12 on 2026-09-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0003_alter_city_currentpopulation"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="urban_area",
            field=models.FloatField(
                help_text="Urban area in square kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="urban_area",
            field=models.FloatField(
                help_text="Urban area in square kilometers", null=True
            ),
        ),
        migrations.AddField(
            model_name="province",
            name="urban_area",
            field=models.FloatField(
                help_text="Urban area in square kilometers", null=True
            ),
        ),
    ]
