# Generated by Django 5.2.12 on 2026-10-05 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit backup",
                "verbose_name_plural": "Edit backups",
            },
        ),
        migrations.CreateModel(
            name="EditBackupRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layer_key",
                    models.CharField(
                        help_text="Registry key, e.g. 'builtup.Building'",
                        max_length=100,
                    ),
                ),
                ("object_pk", models.CharField(max_length=64)),
                ("original", models.JSONField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "backup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="mainMap.editbackup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Edit backup row",
                "verbose_name_plural": "Edit backup rows",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("backup", "layer_key", "object_pk"),
                        name="unique_edit_backup_object",
                    )
                ],
            },
        ),
    ]
