# Generated by Django 5.2.7 on 2026-02-06 12:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=100)),
                ('currentPopulation', models.IntegerField(help_text='Total current population in the city')),
                ('area_km2', models.FloatField(help_text='Area in square kilometers', null=True)),
                ('populationDensity', models.FloatField(help_text='Population density in people per square kilometer', null=True)),
                ('populationDate', models.DateField(null=True)),
                ('popGrowthRate', models.FloatField(help_text='Growth rate in % per year', null=True)),
                ('urbanizationRate', models.FloatField(help_text='Urbanization rate in % per year', null=True)),
                ('urban_area', models.FloatField(help_text='Urban area in square kilometers', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='DigitalElevationModelWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Base WMS endpoint URL', max_length=500)),
                ('layers_param', models.CharField(help_text='WMS layers parameter', max_length=200)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('legend_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opacity', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Digital Elevation Model WMS Layer',
                'verbose_name_plural': 'Digital Elevation Model WMS Layers',
            },
        ),
        migrations.CreateModel(
            name='DigitalSurfaceModelWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Base WMS endpoint URL', max_length=500)),
                ('layers_param', models.CharField(help_text='WMS layers parameter', max_length=200)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('legend_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opacity', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Digital Surface Model WMS Layer',
                'verbose_name_plural': 'Digital Surface Model WMS Layers',
            },
        ),
        migrations.CreateModel(
            name='LandCoverClasses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(help_text="Name of the land cover class (e.g., 'Urban', 'Forest', 'Agriculture', etc.)", max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the land cover class')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LandCoverWMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Base WMS endpoint URL', max_length=500)),
                ('layers_param', models.CharField(help_text='WMS layers parameter', max_length=200)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('legend_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opacity', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Land Cover WMS Layer',
                'verbose_name_plural': 'Land Cover WMS Layers',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('regionName', models.CharField(max_length=100)),
                ('currentPopulation', models.IntegerField(help_text='Total current population in the region', null=True, verbose_name='Current Population')),
                ('populationDensity', models.FloatField(help_text='Population density in people per square kilometer', null=True, verbose_name='Population Density')),
                ('populationDate', models.DateField(help_text='Date of the population data', null=True, verbose_name='Population Date')),
                ('area_km2', models.FloatField(help_text='Area in square kilometers', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='SurfaceMaterialProperties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(help_text="Name of the material (e.g., 'Concrete', 'Asphalt', 'Grass', etc.)", max_length=100)),
                ('albedo', models.FloatField(help_text='Albedo value (0-1) representing the reflectivity of the material')),
                ('thermal_conductivity', models.FloatField(help_text='Thermal conductivity in W/(m*K)')),
                ('specific_heat_capacity', models.FloatField(help_text='Specific heat capacity in J/(kg*K)')),
                ('density', models.FloatField(help_text='Density in kg/m3')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WallMaterialProperties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('material_name', models.CharField(help_text="Name of the wall material (e.g., 'Brick', 'Wood', 'Insulated Panel', etc.)", max_length=100)),
                ('thermal_conductivity', models.FloatField(help_text='Thermal conductivity in W/(m*K)')),
                ('specific_heat_capacity', models.FloatField(help_text='Specific heat capacity in J/(kg*K)')),
                ('density', models.FloatField(help_text='Density in kg/m3')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhoodName', models.CharField(help_text='Name of the neighborhood', max_length=100)),
                ('currentPopulation', models.IntegerField(help_text='Current population in the neighborhood')),
                ('populationDate', models.DateField(null=True)),
                ('area_km2', models.FloatField(help_text='Area in square kilometers')),
                ('populationDensity', models.FloatField(help_text='Population density in people per square kilometer')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(help_text='City code from common.City', on_delete=django.db.models.deletion.DO_NOTHING, to='common.city')),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
            },
        ),
        migrations.CreateModel(
            name='LandCoverRaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing land cover classification values', null=True, srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(help_text='Region code from common.Region', on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSurfaceModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('dsm_raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing surface elevation values', null=True, srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(help_text='Region code from common.Region', on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalElevationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('dem_raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing elevation values', null=True, srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(help_text='Region code from common.Region', on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(help_text='Region code from common.Region', on_delete=django.db.models.deletion.CASCADE, to='common.region'),
        ),
        migrations.CreateModel(
            name='LandCoverVector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('land_use', models.CharField(help_text="Land use type (e.g., 'Residential', 'Commercial', 'Industrial', 'Park', etc.)", max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('percentage', models.FloatField(help_text='Percentage of the region covered by this land cover type')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('land_cover_type', models.ForeignKey(help_text="Type of land cover (e.g., 'Urban', 'Forest', 'Agriculture', etc.)", on_delete=django.db.models.deletion.DO_NOTHING, to='common.landcoverclasses')),
                ('region', models.ForeignKey(help_text='Region code from common.Region', on_delete=django.db.models.deletion.DO_NOTHING, to='common.region')),
                ('material', models.ForeignKey(help_text='Material properties of the land cover type', on_delete=django.db.models.deletion.DO_NOTHING, to='common.surfacematerialproperties')),
            ],
        ),
    ]
