# Generated by Django 5.2.7 on 2025-11-05 12:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cityName", models.CharField(max_length=100)),
                ("currentPopulation", models.IntegerField()),
                ("area_km2", models.FloatField()),
                ("populationDensity", models.FloatField()),
                ("popYR2020", models.IntegerField()),
                ("popGrowthRate", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28892),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "City",
                "verbose_name_plural": "Cities",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("regionName", models.CharField(max_length=100)),
                ("population", models.IntegerField()),
                ("area_km2", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28892),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("neighborhoodName", models.CharField(max_length=100)),
                ("currentPopulation", models.IntegerField()),
                ("area_km2", models.FloatField()),
                ("populationDensity", models.FloatField()),
                ("popYR2020", models.IntegerField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28892),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="common.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ElectricityCost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("cost_EUR_kWh", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.region",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.region"
            ),
        ),
    ]
