# Generated by Django 5.2.12 on 2026-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalCosts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price_EUR_kg_CO2", models.FloatField()),
                ("price_EUR_price_EUR_droughtDamage_m3", models.FloatField()),
            ],
        ),
    ]
