# Generated by Django 5.2.7 on 2025-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="neighborhood",
            options={
                "verbose_name": "Neighborhood",
                "verbose_name_plural": "Neighborhoods",
            },
        ),
        migrations.RenameField(
            model_name="region",
            old_name="population",
            new_name="currentPopulation",
        ),
        migrations.AddField(
            model_name="region",
            name="populationDensity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
