# Generated by Django 5.2.7 on 2026-02-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surfacematerialproperties",
            options={
                "verbose_name": "Surface Material Properties",
                "verbose_name_plural": "Surface Material Properties",
            },
        ),
        migrations.AlterModelOptions(
            name="wallmaterialproperties",
            options={
                "verbose_name": "Wall Material Properties",
                "verbose_name_plural": "Wall Material Properties",
            },
        ),
    ]
