# Generated by Django 5.2.7 on 2026-01-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_neighborhood_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="area_km2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="popGrowthRate",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="popYR2020",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="populationDensity",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="area_km2",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="currentPopulation",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="populationDensity",
            field=models.FloatField(null=True),
        ),
    ]
