# Generated by Django 5.2.7 on 2026-03-26 09:33

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_environmentalcosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='city',
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('districtName', models.CharField(help_text='Name of the district', max_length=100)),
                ('currentPopulation', models.IntegerField(help_text='Current population in the district')),
                ('populationDate', models.DateField(null=True)),
                ('area_km2', models.FloatField(help_text='Area in square kilometers')),
                ('populationDensity', models.FloatField(help_text='Population density in people per square kilometer')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('city', models.ForeignKey(help_text='City code from common.City', on_delete=django.db.models.deletion.DO_NOTHING, to='common.city')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='district',
            field=models.ForeignKey(blank=True, help_text='City code from common.City', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.district'),
        ),
    ]
