# Generated by Django 5.2.12 on 2026-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_remove_neighborhood_city_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
