# Generated by Django 5.2.7 on 2026-01-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_city_area_km2_alter_city_popgrowthrate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="city",
            name="popYR2020",
        ),
        migrations.RemoveField(
            model_name="neighborhood",
            name="popYR2020",
        ),
        migrations.AddField(
            model_name="city",
            name="populationDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="neighborhood",
            name="populationDate",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="populationDate",
            field=models.DateField(null=True),
        ),
    ]
