# Generated by Django 5.2.7 on 2026-01-21 15:35

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_remove_city_popyr2020_remove_neighborhood_popyr2020_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name="region",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
    ]
