# Generated by Django 5.2.12 on 2026-08-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_district_id_alter_neighborhood_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="area_km2",
            field=models.FloatField(
                blank=True, help_text="Area in square kilometers", null=True
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="currentPopulation",
            field=models.IntegerField(
                blank=True, help_text="Current population in the district", null=True
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="populationDensity",
            field=models.FloatField(
                blank=True,
                help_text="Population density in people per square kilometer",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="area_km2",
            field=models.FloatField(
                blank=True, help_text="Area in square kilometers", null=True
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="currentPopulation",
            field=models.IntegerField(
                blank=True,
                help_text="Current population in the neighborhood",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="populationDensity",
            field=models.FloatField(
                blank=True,
                help_text="Population density in people per square kilometer",
                null=True,
            ),
        ),
    ]
