# Generated by Django 5.2.7 on 2026-02-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_city_geom_alter_neighborhood_geom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="area_km2",
            field=models.FloatField(help_text="Area in square kilometers", null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="currentPopulation",
            field=models.IntegerField(help_text="Total current population in the city"),
        ),
        migrations.AlterField(
            model_name="city",
            name="popGrowthRate",
            field=models.FloatField(help_text="Growth rate in % per year", null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="populationDensity",
            field=models.FloatField(
                help_text="Population density in people per square kilometer", null=True
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                help_text="Region code from common.Region",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.region",
            ),
        ),
        migrations.AlterField(
            model_name="electricitycost",
            name="cost_EUR_kWh",
            field=models.FloatField(help_text="Cost in EUR per kilowatt-hour"),
        ),
        migrations.AlterField(
            model_name="electricitycost",
            name="region",
            field=models.ForeignKey(
                help_text="Region code from common.Region",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.region",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="area_km2",
            field=models.FloatField(help_text="Area in square kilometers"),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="city",
            field=models.ForeignKey(
                help_text="City code from common.City",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="currentPopulation",
            field=models.IntegerField(
                help_text="Current population in the neighborhood"
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="neighborhoodName",
            field=models.CharField(
                help_text="Name of the neighborhood", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="populationDensity",
            field=models.FloatField(
                help_text="Population density in people per square kilometer"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="area_km2",
            field=models.FloatField(help_text="Area in square kilometers", null=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="currentPopulation",
            field=models.IntegerField(
                help_text="Total current population in the region",
                null=True,
                verbose_name="Current Population",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="populationDate",
            field=models.DateField(
                help_text="Date of the population data",
                null=True,
                verbose_name="Population Date",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="populationDensity",
            field=models.FloatField(
                help_text="Population density in people per square kilometer",
                null=True,
                verbose_name="Population Density",
            ),
        ),
    ]
