# Generated by Django 5.2.12 on 2026-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_nullable_district_neighborhood_population"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="cityName",
            field=models.CharField(
                help_text="Name of the city", max_length=100, verbose_name="City Name"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="currentPopulation",
            field=models.IntegerField(
                help_text="Total current population in the city",
                verbose_name="Current Population",
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="populationDensity",
            field=models.FloatField(
                help_text="Population density in people per square kilometer",
                null=True,
                verbose_name="Population Density",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="districtName",
            field=models.CharField(
                help_text="Name of the district",
                max_length=100,
                verbose_name="District Name",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="populationDensity",
            field=models.FloatField(
                blank=True,
                help_text="Population density in people per square kilometer",
                null=True,
                verbose_name="Population Density",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="currentPopulation",
            field=models.IntegerField(
                blank=True,
                help_text="Current population in the neighborhood",
                null=True,
                verbose_name="Current Population",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="neighborhoodName",
            field=models.CharField(
                help_text="Name of the neighborhood",
                max_length=100,
                verbose_name="Neighborhood Name",
            ),
        ),
        migrations.AlterField(
            model_name="neighborhood",
            name="populationDensity",
            field=models.FloatField(
                blank=True,
                help_text="Population density in people per square kilometer",
                null=True,
                verbose_name="Population Density",
            ),
        ),
    ]
