# Generated by Django 5.2.12 on 2026-09-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_city_cityname_alter_city_currentpopulation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalelevationmodel",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalsurfacemodel",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="cog_path",
            field=models.CharField(
                blank=True,
                help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                max_length=500,
                null=True,
            ),
        ),
    ]
