# Generated by Django 5.2.7 on 2026-02-05 16:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_city_area_km2_alter_city_currentpopulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='urbanizationRate',
            field=models.FloatField(help_text='Urbanization rate in % per year', null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name='region',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
    ]
