# Generated by Django 5.2.12 on 2026-09-07 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_digitalelevationmodel_cog_path_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SatelliteImagery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing satellite imagery",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "Province",
                    models.ForeignKey(
                        help_text="Province code from common.Province",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.province",
                    ),
                ),
            ],
        ),
    ]
