# Generated by Django 5.2.12 on 2026-09-08 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_satelliteimagery"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="digitalelevationmodel",
            name="Province",
        ),
        migrations.RemoveField(
            model_name="digitalsurfacemodel",
            name="Province",
        ),
        migrations.RemoveField(
            model_name="landcoverraster",
            name="Province",
        ),
        migrations.RemoveField(
            model_name="landcovervector",
            name="Province",
        ),
        migrations.RemoveField(
            model_name="satelliteimagery",
            name="Province",
        ),
        migrations.AddField(
            model_name="digitalelevationmodel",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="digitalelevationmodel",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Acquisition/generation date of the elevation model",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalelevationmodel",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalelevationmodel",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Data provider of the raster (e.g., 'AHN4 (PDOK)')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalsurfacemodel",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="digitalsurfacemodel",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Acquisition/generation date of the surface model",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalsurfacemodel",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="digitalsurfacemodel",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Data provider of the raster (e.g., 'AHN4 (PDOK)')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Acquisition/generation date of the raster",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="index",
            field=models.CharField(
                blank=True,
                help_text="Dataset or index represented by the raster (e.g., 'LGN2021', 'WORLDCOVER_2021_MAP', 'NDVI', 'lossyear')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the raster in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcoverraster",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Data provider of the raster (e.g., 'PDOK', 'Sentinel-2', 'Google Earth Engine')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="landcovervector",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="satelliteimagery",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
        migrations.AddField(
            model_name="satelliteimagery",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="Acquisition date/time of the satellite imagery",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satelliteimagery",
            name="index",
            field=models.CharField(
                blank=True,
                help_text="Type of satellite imagery index/product (e.g., 'TrueColor', 'NDVI', 'EVI', 'NDWI', etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satelliteimagery",
            name="resolution",
            field=models.FloatField(
                blank=True,
                help_text="Spatial resolution of the imagery in meters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="satelliteimagery",
            name="satellite_type",
            field=models.CharField(
                blank=True,
                help_text="Satellite or sensor that captured the imagery (e.g., 'Sentinel-2', 'Landsat', 'MODIS', etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="digitalelevationmodelwms",
            name="color",
            field=models.CharField(default="#272727", max_length=7),
        ),
        migrations.AlterField(
            model_name="landcovervector",
            name="percentage",
            field=models.FloatField(
                help_text="Percentage of the City covered by this land cover type"
            ),
        ),
    ]
