# Generated by Django 5.2.12 on 2026-09-14 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_remove_digitalelevationmodel_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landcovervector",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="Material properties of the land cover type, where known",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.surfacematerialproperties",
            ),
        ),
    ]
