# Generated by Django 5.2.12 on 2026-09-15 12:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableFreshWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "SourceName",
                    models.CharField(
                        help_text="Name of the water source. Corresponds to the Balance Area ",
                        max_length=100,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "infiltrationRate_cm_h",
                    models.FloatField(
                        help_text="Infiltration rate in centimeters per hour"
                    ),
                ),
                (
                    "infiltrationDepth_cm",
                    models.FloatField(help_text="Infiltration depth in centimeters"),
                ),
                (
                    "totalQuantity_Mm3",
                    models.FloatField(
                        help_text="total quantity in million cubic meters"
                    ),
                ),
                (
                    "yield_Mm3_year",
                    models.FloatField(
                        help_text="Yield in million cubic meters per year"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Available Fresh Water",
                "verbose_name_plural": "Available Fresh Water",
            },
        ),
        migrations.CreateModel(
            name="ImportedWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sourceName",
                    models.CharField(
                        help_text="Name of the imported water source", max_length=100
                    ),
                ),
                (
                    "quantity_m3_d",
                    models.FloatField(help_text="Quantity in cubic meters per day"),
                ),
                (
                    "price_EUR_m3",
                    models.FloatField(help_text="Price in EUR per cubic meter"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Imported Water",
                "verbose_name_plural": "Imported Water",
            },
        ),
        migrations.CreateModel(
            name="NonRevenueWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Apparent"), ("R", "Real")],
                        default="A",
                        help_text="Type of loss (Real or Apparent)",
                        max_length=100,
                    ),
                ),
                (
                    "specificLoss",
                    models.CharField(
                        choices=[
                            ("CM", "Meter Innacurracy"),
                            ("UA", "Unathorized consumption"),
                            ("DE", "Data Handling errors"),
                            ("OT", "Other"),
                            ("LP", "Leakage on Mains"),
                            ("LS", "Leakage and overflows at storage"),
                            ("LM", "Leakage at meter connection"),
                        ],
                        default="CM",
                        help_text="Specific loss category",
                        max_length=100,
                    ),
                ),
                (
                    "loss_Quantity_m3",
                    models.FloatField(
                        help_text="Loss quantity in cubic meters per day"
                    ),
                ),
                (
                    "WaterCost_EUR_day",
                    models.FloatField(help_text="Water cost in EUR per day"),
                ),
                (
                    "UnavoidableLossses_PCT",
                    models.FloatField(help_text="Unavoidable losses in percentage"),
                ),
                (
                    "ILI",
                    models.FloatField(
                        blank=True, help_text="Infrastructure Leakage Index", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Non Revenue Water",
                "verbose_name_plural": "Non Revenue Water Records",
            },
        ),
        migrations.CreateModel(
            name="OPEX",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField(help_text="Year of operation")),
                (
                    "UnitaryOPEX_EUR_m3",
                    models.FloatField(help_text="Unitary OPEX in EUR per cubic meter"),
                ),
                ("totalOPEX_EUR", models.FloatField(help_text="Total OPEX in EUR")),
                (
                    "OPEX_recovered_EUR",
                    models.FloatField(help_text="OPEX recovered in EUR", null=True),
                ),
                (
                    "OPEX_recovered_PCT",
                    models.FloatField(help_text="OPEX recovered in percent", null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "OPEX",
                "verbose_name_plural": "OPEX Records",
            },
        ),
        migrations.CreateModel(
            name="Watershed",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the watershed", max_length=100),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Watershed",
                "verbose_name_plural": "Watersheds",
            },
        ),
        migrations.CreateModel(
            name="WaterTreatment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "UnitaryOPEX_EUR_m3",
                    models.FloatField(help_text="Unitary OPEX in EUR per cubic meter"),
                ),
                (
                    "treatment_efficiency",
                    models.FloatField(help_text="Treatment efficiency in percent"),
                ),
                (
                    "samplesWaterQuality_OK",
                    models.IntegerField(
                        help_text="Number of samples with OK water quality"
                    ),
                ),
                (
                    "samplesWaterQualityTaken",
                    models.IntegerField(help_text="Total number of samples taken"),
                ),
                (
                    "EnergyConsumption_MW_day",
                    models.FloatField(
                        help_text="Energy consumption in megawatt-hours per day"
                    ),
                ),
                (
                    "acceptanceRate",
                    models.FloatField(help_text="User Acceptance rate in percent"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Treatment",
                "verbose_name_plural": "Water Treatment Records",
            },
        ),
        migrations.CreateModel(
            name="WMSLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#4a90d9", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "WMS Layer",
                "verbose_name_plural": "WMS Layers",
            },
        ),
        migrations.CreateModel(
            name="AreaAffectedDrought",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                ("areaName", models.CharField(max_length=100)),
                (
                    "SensibilityLevel",
                    models.IntegerField(
                        choices=[
                            (0, "Not Affected"),
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        default=0,
                        help_text="Sensibility level to drought",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "areaAffected_km2",
                    models.FloatField(help_text="Area affected in square kilometers"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "Province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Area Affected by Drought",
                "verbose_name_plural": "Area Affected by Drought Records",
            },
        ),
        migrations.CreateModel(
            name="ConsumptionCapita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "consumption_capita_L_d",
                    models.FloatField(help_text="in liters per person per day"),
                ),
                (
                    "total_consumption_m3_yr",
                    models.FloatField(
                        blank=True, help_text="in cubic meters per year", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumption Capita",
                "verbose_name_plural": "Consumption Capita",
            },
        ),
        migrations.CreateModel(
            name="CoverageWaterSupply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "buffer_m",
                    models.FloatField(
                        default=500, help_text="Buffer distance around pipes in meters"
                    ),
                ),
                (
                    "coveredArea_km2",
                    models.FloatField(help_text="Covered area in square kilometers"),
                ),
                (
                    "households_covered",
                    models.IntegerField(
                        default=0,
                        help_text="Number of households within the service area",
                    ),
                ),
                (
                    "households_total",
                    models.IntegerField(
                        default=0, help_text="Total households in the city"
                    ),
                ),
                (
                    "coveragePCT",
                    models.FloatField(help_text="Coverage of users in percentage"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True,
                        help_text="Dissolved buffer polygon around pipe network",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coverage Water Supply",
                "verbose_name_plural": "Coverage Water Supply Records",
            },
        ),
        migrations.CreateModel(
            name="ExtractionWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
                ),
                (
                    "stationName",
                    models.CharField(
                        help_text="Name of the extraction station or well",
                        max_length=100,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                        ],
                        default="residential",
                        help_text="Type of extraction (Residential, Commercial, Industrial)",
                        max_length=100,
                    ),
                ),
                (
                    "permit_Mm3_yr",
                    models.FloatField(
                        blank=True,
                        help_text="Maximum permitted extraction in Mm³/yr",
                        null=True,
                    ),
                ),
                (
                    "agreement_Mm3_yr",
                    models.FloatField(
                        blank=True, help_text="Agreed extraction in Mm³/yr", null=True
                    ),
                ),
                (
                    "current_extraction_Mm3_yr",
                    models.FloatField(
                        blank=True,
                        help_text="Current actual extraction in Mm³/yr",
                        null=True,
                    ),
                ),
                (
                    "num_wells",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of individual wells at this station",
                        null=True,
                    ),
                ),
                (
                    "pumpflow_m3_s",
                    models.FloatField(help_text="Pump flow in cubic meters per second"),
                ),
                (
                    "pumpMaxFlow_m3_s",
                    models.FloatField(
                        help_text="Maximum pump flow in cubic meters per second"
                    ),
                ),
                (
                    "OperationTime_h_day",
                    models.FloatField(help_text="Operation time in hours per day"),
                ),
                ("depth_m", models.FloatField(help_text="Depth in meters")),
                (
                    "pumpEfficiency",
                    models.FloatField(help_text="Pump efficiency in percent"),
                ),
                (
                    "pumpEnergyRate_kWh_h",
                    models.FloatField(
                        help_text="Pump energy rate in kilowatt-hours per hour"
                    ),
                ),
                (
                    "pumpEmissionRate_kg_CO2_h",
                    models.FloatField(
                        help_text="Pump emission rate in kilograms of CO2 per hour",
                        null=True,
                    ),
                ),
                (
                    "pumpEmmissionFactor_kg_CO2_kWh",
                    models.FloatField(
                        help_text="Pump emission factor in kilograms of CO2 per kilowatt-hour",
                        null=True,
                    ),
                ),
                (
                    "pumpEmission_day_kg_CO2",
                    models.FloatField(
                        help_text="Pump emissions in kilograms of CO2 per day",
                        null=True,
                    ),
                ),
                (
                    "pumpEmission_year_kg_CO2",
                    models.FloatField(
                        help_text="Pump emissions in kilograms of CO2 per year",
                        null=True,
                    ),
                ),
                (
                    "opex_EUR_m3",
                    models.FloatField(
                        blank=True,
                        help_text="Total OPEX in EUR per m³ (labor+energy+chemicals+tax)",
                        null=True,
                    ),
                ),
                ("labor_EUR_m3", models.FloatField(blank=True, null=True)),
                ("energy_EUR_m3", models.FloatField(blank=True, null=True)),
                ("chemicals_EUR_m3", models.FloatField(blank=True, null=True)),
                ("tax_EUR_m3", models.FloatField(blank=True, null=True)),
                (
                    "co2_cost_EUR_m3",
                    models.FloatField(
                        blank=True,
                        help_text="CO₂ emission cost in EUR per m³",
                        null=True,
                    ),
                ),
                (
                    "drought_damage_EUR_m3",
                    models.FloatField(
                        blank=True,
                        help_text="Drought damage cost in EUR per m³",
                        null=True,
                    ),
                ),
                (
                    "inside_property",
                    models.BooleanField(
                        default=True, help_text="Whether the well is on owned land"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this well is currently active"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater. Corresponds to the Balance Area",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.availablefreshwater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extraction Water",
                "verbose_name_plural": "Extraction Water",
            },
        ),
        migrations.CreateModel(
            name="SupplySecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("supply_security_pct", models.FloatField(help_text="in percent")),
                ("security_goal_pct", models.FloatField(help_text="in percent")),
                ("service_time_hours", models.FloatField(help_text="in hours per day")),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supply Security",
                "verbose_name_plural": "Supply Security Records",
            },
        ),
        migrations.CreateModel(
            name="TotalWaterDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "demandDay",
                    models.FloatField(help_text="in Million cubic meters per day"),
                ),
                (
                    "demandYR",
                    models.FloatField(
                        help_text="in Million cubic meters per year", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        help_text="City code from administrative.City",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Water Demand",
                "verbose_name_plural": "Total Water Demand Records",
            },
        ),
        migrations.CreateModel(
            name="TotalWaterProduction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "imported_boolean",
                    models.BooleanField(
                        default=False, help_text="Are there imported sources?"
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "productionDay",
                    models.FloatField(help_text="in Million cubic meters per day"),
                ),
                (
                    "productionYR",
                    models.FloatField(
                        help_text="in Million cubic meters per year", null=True
                    ),
                ),
                ("costDay", models.FloatField(help_text="in EUR per day", null=True)),
                ("costYR", models.FloatField(help_text="in EUR per year", null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ManyToManyField(
                        help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater",
                        to="watersupply.availablefreshwater",
                    ),
                ),
                (
                    "source_imported",
                    models.ManyToManyField(
                        blank=True,
                        help_text="ImportedFreshWater ID from watersupply.ImportedFreshWater",
                        to="watersupply.importedwater",
                    ),
                ),
            ],
            options={
                "verbose_name": "Total Water Production",
                "verbose_name_plural": "Total Water Production Records",
            },
        ),
        migrations.CreateModel(
            name="UsersLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "usersTotal",
                    models.IntegerField(
                        help_text="Total number of users in the neighborhood"
                    ),
                ),
                (
                    "ResidentialUsers",
                    models.IntegerField(
                        help_text="Number of residential users", null=True
                    ),
                ),
                (
                    "CommercialUsers",
                    models.IntegerField(
                        help_text="Number of commercial users", null=True
                    ),
                ),
                (
                    "IndustrialUsers",
                    models.IntegerField(
                        help_text="Number of industrial users", null=True
                    ),
                ),
                (
                    "populationServed",
                    models.IntegerField(
                        help_text="Population served in the neighborhood", null=True
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        help_text="Neighborhood code from administrative.Neighborhood",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Users Location",
                "verbose_name_plural": "Users Locations",
            },
        ),
        migrations.CreateModel(
            name="MeteredResidential",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "installed_meters",
                    models.IntegerField(help_text="Number of installed meters"),
                ),
                (
                    "functional_meters",
                    models.IntegerField(help_text="Number of functional meters"),
                ),
                (
                    "collected_meters",
                    models.IntegerField(help_text="Number of collected meters"),
                ),
                (
                    "userTariff_EUR_m3",
                    models.FloatField(help_text="in EUR per cubic meter"),
                ),
                ("userAffordability_PCT", models.FloatField(help_text="in percent")),
                (
                    "consumption_m3_yr",
                    models.FloatField(
                        blank=True,
                        help_text="Annual consumption volume billed (m³/yr)",
                        null=True,
                    ),
                ),
                (
                    "Recovery_EUR",
                    models.FloatField(
                        blank=True,
                        help_text="Annual revenue recovered in EUR",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "userLocation",
                    models.ForeignKey(
                        help_text="UsersLocation ID from watersupply.UsersLocation",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.userslocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metered Residential",
                "verbose_name_plural": "Metered Residential",
            },
        ),
        migrations.AddField(
            model_name="availablefreshwater",
            name="watershed",
            field=models.ForeignKey(
                help_text="Watershed code from watersupply.Watershed. ",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.watershed",
            ),
        ),
        migrations.CreateModel(
            name="PipeNetwork",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("length_km", models.FloatField(help_text="in kilometers")),
                (
                    "diameter_mm",
                    models.FloatField(
                        blank=True, help_text="Pipe diameter in millimeters", null=True
                    ),
                ),
                (
                    "diameter_in",
                    models.FloatField(
                        blank=True, help_text="Pipe diameter in inches", null=True
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=28992
                    ),
                ),
                (
                    "maitenanceCost_EUR_km",
                    models.FloatField(help_text="in EUR per kilometer", null=True),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        help_text="ExtractionWater ID from watersupply.ExtractionWater",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.extractionwater",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        help_text="UsersLocation ID from watersupply.UsersLocation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.userslocation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipe Network",
                "verbose_name_plural": "Pipe Networks",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origin", "destination"), name="unique_pipe_network"
                    )
                ],
            },
        ),
    ]
