# Generated by Django 5.2.7 on 2025-11-05 12:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableFreshWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("SourceName", models.CharField(max_length=100)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28892),
                ),
                ("infiltrationRate_cm_h", models.FloatField()),
                ("infiltrationDepth_cm", models.FloatField()),
                ("totalQuantity_Mm3", models.FloatField()),
                ("yield_Mm3_year", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImportedWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sourceName", models.CharField(max_length=100)),
                ("quantity_m3_d", models.FloatField()),
                ("price_EUR_m3", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="NonRevenueWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("A", "Apparent"), ("R", "Real")],
                        default="A",
                        max_length=100,
                    ),
                ),
                (
                    "specificLoss",
                    models.CharField(
                        choices=[
                            ("CM", "Meter Innacurracy"),
                            ("UA", "Unathorized consumption"),
                            ("DE", "Data Handling errors"),
                            ("OT", "Other"),
                            ("LP", "Leakage on Mains"),
                            ("LS", "Leakage and overflows at storage"),
                            ("LM", "Leakage at meter connection"),
                        ],
                        default="CM",
                        max_length=100,
                    ),
                ),
                ("loss_Quantity_m3", models.FloatField()),
                ("WaterCost_EUR_day", models.FloatField()),
                ("UnavoidableLossses_PCT", models.FloatField()),
                ("ILI", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OPEX",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("UnitaryOPEX_EUR_m3", models.FloatField()),
                ("totalOPEX_EUR", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PipeNetwork",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("length_km", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiLineStringField(
                        srid=28892
                    ),
                ),
                ("maitenanceCost_EUR_km", models.FloatField(null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WaterTreatment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("UnitaryOPEX_EUR_m3", models.FloatField()),
                ("treatment_efficiency", models.FloatField()),
                ("samplesWaterQuality_OK", models.IntegerField()),
                ("samplesWaterQualityTaken", models.IntegerField()),
                ("EnergyConsumption_MW_day", models.FloatField()),
                ("acceptanceRate", models.FloatField()),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=28892),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaAffectedDrought",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28892),
                ),
                ("areaName", models.CharField(max_length=100)),
                (
                    "SensibilityLevel",
                    models.IntegerField(
                        choices=[
                            (0, "Not Affected"),
                            (1, "Very Low"),
                            (2, "Low"),
                            (3, "Medium"),
                            (4, "High"),
                            (5, "Very High"),
                        ],
                        default=0,
                    ),
                ),
                ("year", models.IntegerField()),
                ("areaAffected_km2", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ConsumptionCapita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("consumption_capita_L_d", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CoverageWaterSupply",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("coveredArea_km2", models.FloatField()),
                ("year", models.IntegerField()),
                ("coveragePCT", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "Neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.neighborhood",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtractionWater",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=28892),
                ),
                ("stationName", models.CharField(max_length=100)),
                ("pumpflow_m3_s", models.FloatField()),
                ("pumpMaxFlow_m3_s", models.FloatField()),
                ("OperationTime_h_day", models.FloatField()),
                ("depth_m", models.FloatField()),
                ("pumpEfficiency", models.FloatField()),
                ("pumpEnergyRate_kWh_h", models.FloatField()),
                ("pumpEmissionRate_kg_CO2_h", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.availablefreshwater",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplySecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("supply_security_pct", models.FloatField()),
                ("security_goal_pct", models.FloatField()),
                ("service_time_hours", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalWaterDemand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("demandDay", models.FloatField()),
                ("demandYR", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.city"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsersLocation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("usersTotal", models.IntegerField()),
                ("ResidentialUsers", models.IntegerField(null=True)),
                ("CommercialUsers", models.IntegerField(null=True)),
                ("IndustrialUsers", models.IntegerField(null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.neighborhood",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeteredResidential",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("installed_meters", models.IntegerField()),
                ("functional_meters", models.IntegerField()),
                ("collected_meters", models.IntegerField()),
                ("userTariff_EUR_m3", models.FloatField()),
                ("userAffordability_PCT", models.FloatField()),
                ("Recovery_EUR", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.userslocation",
                    ),
                ),
            ],
        ),
    ]
