# Generated by Django 5.2.7 on 2025-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptioncapita",
            name="total_consumption_m3_yr",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="consumptioncapita",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
