# Generated by Django 5.2.7 on 2026-02-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="areaaffecteddrought",
            options={
                "verbose_name": "Area Affected by Drought",
                "verbose_name_plural": "Area Affected by Drought Records",
            },
        ),
        migrations.AlterModelOptions(
            name="availablefreshwater",
            options={
                "verbose_name": "Available Fresh Water",
                "verbose_name_plural": "Available Fresh Water",
            },
        ),
        migrations.AlterModelOptions(
            name="consumptioncapita",
            options={
                "verbose_name": "Consumption Capita",
                "verbose_name_plural": "Consumption Capita",
            },
        ),
        migrations.AlterModelOptions(
            name="coveragewatersupply",
            options={
                "verbose_name": "Coverage Water Supply",
                "verbose_name_plural": "Coverage Water Supply Records",
            },
        ),
        migrations.AlterModelOptions(
            name="extractionwater",
            options={
                "verbose_name": "Extraction Water",
                "verbose_name_plural": "Extraction Water",
            },
        ),
        migrations.AlterModelOptions(
            name="importedwater",
            options={
                "verbose_name": "Imported Water",
                "verbose_name_plural": "Imported Water",
            },
        ),
        migrations.AlterModelOptions(
            name="meteredresidential",
            options={
                "verbose_name": "Metered Residential",
                "verbose_name_plural": "Metered Residential",
            },
        ),
        migrations.AlterModelOptions(
            name="nonrevenuewater",
            options={
                "verbose_name": "Non Revenue Water",
                "verbose_name_plural": "Non Revenue Water Records",
            },
        ),
        migrations.AlterModelOptions(
            name="opex",
            options={"verbose_name": "OPEX", "verbose_name_plural": "OPEX Records"},
        ),
        migrations.AlterModelOptions(
            name="pipenetwork",
            options={
                "verbose_name": "Pipe Network",
                "verbose_name_plural": "Pipe Networks",
            },
        ),
        migrations.AlterModelOptions(
            name="supplysecurity",
            options={
                "verbose_name": "Supply Security",
                "verbose_name_plural": "Supply Security Records",
            },
        ),
        migrations.AlterModelOptions(
            name="totalwaterdemand",
            options={
                "verbose_name": "Total Water Demand",
                "verbose_name_plural": "Total Water Demand Records",
            },
        ),
        migrations.AlterModelOptions(
            name="totalwaterproduction",
            options={
                "verbose_name": "Total Water Production",
                "verbose_name_plural": "Total Water Production Records",
            },
        ),
        migrations.AlterModelOptions(
            name="userslocation",
            options={
                "verbose_name": "Users Location",
                "verbose_name_plural": "Users Locations",
            },
        ),
        migrations.AlterModelOptions(
            name="watertreatment",
            options={
                "verbose_name": "Water Treatment",
                "verbose_name_plural": "Water Treatment Records",
            },
        ),
    ]
