# Generated by Django 5.2.12 on 2026-10-06 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonrevenuewater",
            name="pipe",
            field=models.ForeignKey(
                blank=True,
                help_text="Pipe where the real loss (leakage) is presumed to occur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="losses",
                to="watersupply.pipenetwork",
            ),
        ),
    ]
