# Generated by Django 5.2.12 on 2026-03-10 15:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watershed",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the watershed", max_length=100),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Watershed",
                "verbose_name_plural": "Watersheds",
            },
        ),
        migrations.RemoveField(
            model_name="availablefreshwater",
            name="Province",
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="agreement_Mm3_yr",
            field=models.FloatField(
                blank=True, help_text="Agreed extraction in Mm³/yr", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="chemicals_EUR_m3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="co2_cost_EUR_m3",
            field=models.FloatField(
                blank=True, help_text="CO₂ emission cost in EUR per m³", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="current_extraction_Mm3_yr",
            field=models.FloatField(
                blank=True, help_text="Current actual extraction in Mm³/yr", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="drought_damage_EUR_m3",
            field=models.FloatField(
                blank=True, help_text="Drought damage cost in EUR per m³", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="energy_EUR_m3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="inside_property",
            field=models.BooleanField(
                default=True, help_text="Whether the well is on owned land"
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this well is currently active"
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="labor_EUR_m3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="num_wells",
            field=models.IntegerField(
                blank=True,
                help_text="Number of individual wells at this station",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="opex_EUR_m3",
            field=models.FloatField(
                blank=True,
                help_text="Total OPEX in EUR per m³ (labor+energy+chemicals+tax)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="permit_Mm3_yr",
            field=models.FloatField(
                blank=True,
                help_text="Maximum permitted extraction in Mm³/yr",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="tax_EUR_m3",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="type",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                ],
                default="residential",
                help_text="Type of extraction (Residential, Commercial, Industrial)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="pipenetwork",
            name="destination",
            field=models.ForeignKey(
                help_text="UsersLocation ID from common.UsersLocation",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.userslocation",
            ),
        ),
        migrations.AddField(
            model_name="pipenetwork",
            name="diameter_in",
            field=models.FloatField(
                blank=True, help_text="Pipe diameter in inches", null=True
            ),
        ),
        migrations.AddField(
            model_name="pipenetwork",
            name="diameter_mm",
            field=models.FloatField(
                blank=True, help_text="Pipe diameter in millimeters", null=True
            ),
        ),
        migrations.AddField(
            model_name="pipenetwork",
            name="origin",
            field=models.ForeignKey(
                help_text="ExtractionWater ID from watersupply.ExtractionWater",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.extractionwater",
            ),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="SourceName",
            field=models.CharField(
                help_text="Name of the water source. Corresponds to the Balance Area ",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="source",
            field=models.ForeignKey(
                help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater. Corresponds to the Balance Area",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.availablefreshwater",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipenetwork",
            constraint=models.UniqueConstraint(
                fields=("origin", "destination"), name="unique_pipe_network"
            ),
        ),
        migrations.AddField(
            model_name="availablefreshwater",
            name="watershed",
            field=models.ForeignKey(
                help_text="Watershed code from common.Watershed. ",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.watershed",
            ),
        ),
    ]
