# Generated by Django 5.2.12 on 2026-03-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0002_watershed_remove_availablefreshwater_province_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractionwater",
            name="stationName",
            field=models.CharField(
                help_text="Name of the extraction station or well", max_length=100
            ),
        ),
    ]
