# Generated by Django 5.2.7 on 2026-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0002_alter_areaaffecteddrought_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="totalwaterproduction",
            name="imported_boolean",
            field=models.BooleanField(
                default=False, help_text="Are there imported sources?"
            ),
        ),
        migrations.AddField(
            model_name="totalwaterproduction",
            name="source_imported",
            field=models.ManyToManyField(
                blank=True,
                help_text="ImportedFreshWater ID from watersupply.ImportedFreshWater",
                to="watersupply.importedwater",
            ),
        ),
        migrations.RemoveField(
            model_name="totalwaterproduction",
            name="source",
        ),
        migrations.AddField(
            model_name="totalwaterproduction",
            name="source",
            field=models.ManyToManyField(
                help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater",
                to="watersupply.availablefreshwater",
            ),
        ),
    ]
