# Generated by Django 5.2.7 on 2026-01-20 15:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0002_consumptioncapita_total_consumption_m3_yr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaaffecteddrought",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
        ),
        migrations.AlterField(
            model_name="pipenetwork",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=28992),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
        ),
    ]
