# Generated by Django 5.2.12 on 2026-03-11 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0003_alter_extractionwater_stationname"),
    ]

    operations = [
        migrations.AddField(
            model_name="importedwater",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="importedwater",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="meteredresidential",
            name="consumption_m3_yr",
            field=models.FloatField(
                blank=True,
                help_text="Annual consumption volume billed (m³/yr)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="Recovery_EUR",
            field=models.FloatField(
                blank=True, help_text="Annual revenue recovered in EUR", null=True
            ),
        ),
    ]
