# Generated by Django 5.2.7 on 2026-02-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0003_alter_areaaffecteddrought_geom_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WMSLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#4a90d9", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "WMS Layer",
                "verbose_name_plural": "WMS Layers",
            },
        ),
    ]
