# Generated by Django 5.2.7 on 2026-02-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0004_wmslayer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="areaaffecteddrought",
            name="SensibilityLevel",
            field=models.IntegerField(
                choices=[
                    (0, "Not Affected"),
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Medium"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                default=0,
                help_text="Sensibility level to drought",
            ),
        ),
        migrations.AlterField(
            model_name="areaaffecteddrought",
            name="areaAffected_km2",
            field=models.FloatField(help_text="Area affected in square kilometers"),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="infiltrationDepth_cm",
            field=models.FloatField(help_text="Infiltration depth in centimeters"),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="infiltrationRate_cm_h",
            field=models.FloatField(
                help_text="Infiltration rate in centimeters per hour"
            ),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="totalQuantity_Mm3",
            field=models.FloatField(help_text="total quantity in million cubic meters"),
        ),
        migrations.AlterField(
            model_name="availablefreshwater",
            name="yield_Mm3_year",
            field=models.FloatField(help_text="Yield in million cubic meters per year"),
        ),
        migrations.AlterField(
            model_name="consumptioncapita",
            name="consumption_capita_L_d",
            field=models.FloatField(help_text="in liters per person per day"),
        ),
        migrations.AlterField(
            model_name="consumptioncapita",
            name="total_consumption_m3_yr",
            field=models.FloatField(
                blank=True, help_text="in cubic meters per year", null=True
            ),
        ),
        migrations.AlterField(
            model_name="coveragewatersupply",
            name="coveragePCT",
            field=models.FloatField(help_text="Coverage of users in percentage"),
        ),
        migrations.AlterField(
            model_name="coveragewatersupply",
            name="coveredArea_km2",
            field=models.FloatField(help_text="Covered area in square kilometers"),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="OperationTime_h_day",
            field=models.FloatField(help_text="Operation time in hours per day"),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="depth_m",
            field=models.FloatField(help_text="Depth in meters"),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpEfficiency",
            field=models.FloatField(help_text="Pump efficiency in percent"),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpEmissionRate_kg_CO2_h",
            field=models.FloatField(
                help_text="Pump emission rate in kilograms of CO2 per hour"
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpEnergyRate_kWh_h",
            field=models.FloatField(
                help_text="Pump energy rate in kilowatt-hours per hour"
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpMaxFlow_m3_s",
            field=models.FloatField(
                help_text="Maximum pump flow in cubic meters per second"
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpflow_m3_s",
            field=models.FloatField(help_text="Pump flow in cubic meters per second"),
        ),
        migrations.AlterField(
            model_name="importedwater",
            name="price_EUR_m3",
            field=models.FloatField(help_text="Price in EUR per cubic meter"),
        ),
        migrations.AlterField(
            model_name="importedwater",
            name="quantity_m3_d",
            field=models.FloatField(help_text="Quantity in cubic meters per day"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="Recovery_EUR",
            field=models.FloatField(help_text="in EUR"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="collected_meters",
            field=models.IntegerField(help_text="Number of collected meters"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="functional_meters",
            field=models.IntegerField(help_text="Number of functional meters"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="installed_meters",
            field=models.IntegerField(help_text="Number of installed meters"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="userAffordability_PCT",
            field=models.FloatField(help_text="in percent"),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="userTariff_EUR_m3",
            field=models.FloatField(help_text="in EUR per cubic meter"),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="ILI",
            field=models.FloatField(help_text="Infrastructure Leakage Index"),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="UnavoidableLossses_PCT",
            field=models.FloatField(help_text="Unavoidable losses in percentage"),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="WaterCost_EUR_day",
            field=models.FloatField(help_text="Water cost in EUR per day"),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="loss_Quantity_m3",
            field=models.FloatField(help_text="Loss quantity in cubic meters per day"),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="specificLoss",
            field=models.CharField(
                choices=[
                    ("CM", "Meter Innacurracy"),
                    ("UA", "Unathorized consumption"),
                    ("DE", "Data Handling errors"),
                    ("OT", "Other"),
                    ("LP", "Leakage on Mains"),
                    ("LS", "Leakage and overflows at storage"),
                    ("LM", "Leakage at meter connection"),
                ],
                default="CM",
                help_text="Specific loss category",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="type",
            field=models.CharField(
                choices=[("A", "Apparent"), ("R", "Real")],
                default="A",
                help_text="Type of loss (Real or Apparent)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="opex",
            name="UnitaryOPEX_EUR_m3",
            field=models.FloatField(help_text="Unitary OPEX in EUR per cubic meter"),
        ),
        migrations.AlterField(
            model_name="opex",
            name="totalOPEX_EUR",
            field=models.FloatField(help_text="Total OPEX in EUR"),
        ),
        migrations.AlterField(
            model_name="opex",
            name="year",
            field=models.IntegerField(help_text="Year of operation"),
        ),
        migrations.AlterField(
            model_name="pipenetwork",
            name="length_km",
            field=models.FloatField(help_text="in kilometers"),
        ),
        migrations.AlterField(
            model_name="pipenetwork",
            name="maitenanceCost_EUR_km",
            field=models.FloatField(help_text="in EUR per kilometer", null=True),
        ),
        migrations.AlterField(
            model_name="supplysecurity",
            name="security_goal_pct",
            field=models.FloatField(help_text="in percent"),
        ),
        migrations.AlterField(
            model_name="supplysecurity",
            name="service_time_hours",
            field=models.FloatField(help_text="in hours per day"),
        ),
        migrations.AlterField(
            model_name="supplysecurity",
            name="supply_security_pct",
            field=models.FloatField(help_text="in percent"),
        ),
        migrations.AlterField(
            model_name="totalwaterdemand",
            name="demandDay",
            field=models.FloatField(help_text="in Million cubic meters per day"),
        ),
        migrations.AlterField(
            model_name="totalwaterdemand",
            name="demandYR",
            field=models.FloatField(
                help_text="in Million cubic meters per year", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userslocation",
            name="CommercialUsers",
            field=models.IntegerField(
                help_text="Number of commercial users", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userslocation",
            name="IndustrialUsers",
            field=models.IntegerField(
                help_text="Number of industrial users", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userslocation",
            name="ResidentialUsers",
            field=models.IntegerField(
                help_text="Number of residential users", null=True
            ),
        ),
        migrations.AlterField(
            model_name="userslocation",
            name="usersTotal",
            field=models.IntegerField(
                help_text="Total number of users in the neighborhood"
            ),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="EnergyConsumption_MW_day",
            field=models.FloatField(
                help_text="Energy consumption in megawatt-hours per day"
            ),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="UnitaryOPEX_EUR_m3",
            field=models.FloatField(help_text="Unitary OPEX in EUR per cubic meter"),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="acceptanceRate",
            field=models.FloatField(help_text="User Acceptance rate in percent"),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="samplesWaterQualityTaken",
            field=models.IntegerField(help_text="Total number of samples taken"),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="samplesWaterQuality_OK",
            field=models.IntegerField(
                help_text="Number of samples with OK water quality"
            ),
        ),
        migrations.AlterField(
            model_name="watertreatment",
            name="treatment_efficiency",
            field=models.FloatField(help_text="Treatment efficiency in percent"),
        ),
    ]
