# Generated by Django 5.2.12 on 2026-03-30 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "watersupply",
            "0004_importedwater_is_active_importedwater_last_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="coveragewatersupply",
            name="buffer_m",
            field=models.FloatField(
                default=500, help_text="Buffer distance around pipes in meters"
            ),
        ),
        migrations.AddField(
            model_name="coveragewatersupply",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text="Dissolved buffer polygon around pipe network",
                null=True,
                srid=28992,
            ),
        ),
        migrations.AddField(
            model_name="coveragewatersupply",
            name="households_covered",
            field=models.IntegerField(
                default=0, help_text="Number of households within the service area"
            ),
        ),
        migrations.AddField(
            model_name="coveragewatersupply",
            name="households_total",
            field=models.IntegerField(
                default=0, help_text="Total households in the city"
            ),
        ),
        migrations.AlterField(
            model_name="nonrevenuewater",
            name="ILI",
            field=models.FloatField(
                blank=True, help_text="Infrastructure Leakage Index", null=True
            ),
        ),
    ]
