# Generated by Django 5.2.7 on 2026-02-03 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_city_area_km2_alter_city_currentpopulation_and_more"),
        ("watersupply", "0005_alter_areaaffecteddrought_sensibilitylevel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="availablefreshwater",
            name="SourceName",
            field=models.CharField(
                help_text="Name of the water source", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="consumptioncapita",
            name="city",
            field=models.ForeignKey(
                help_text="City code from common.City",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.city",
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="stationName",
            field=models.CharField(
                help_text="Name of the extraction station", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="importedwater",
            name="sourceName",
            field=models.CharField(
                help_text="Name of the imported water source", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="meteredresidential",
            name="user",
            field=models.ForeignKey(
                help_text="UsersLocation ID from common.UsersLocation",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.userslocation",
            ),
        ),
        migrations.AlterField(
            model_name="supplysecurity",
            name="city",
            field=models.ForeignKey(
                help_text="City code from common.City",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.city",
            ),
        ),
        migrations.AlterField(
            model_name="totalwaterdemand",
            name="city",
            field=models.ForeignKey(
                help_text="City code from common.City",
                on_delete=django.db.models.deletion.CASCADE,
                to="common.city",
            ),
        ),
        migrations.AlterField(
            model_name="userslocation",
            name="neighborhood",
            field=models.ForeignKey(
                help_text="Neighborhood code from common.Neighborhood",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.neighborhood",
            ),
        ),
    ]
