# Generated by Django 5.2.7 on 2026-02-03 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watersupply", "0006_alter_availablefreshwater_sourcename_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractionwater",
            name="pumpEmission_day_kg_CO2",
            field=models.FloatField(
                help_text="Pump emissions in kilograms of CO2 per day", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="pumpEmission_year_kg_CO2",
            field=models.FloatField(
                help_text="Pump emissions in kilograms of CO2 per year", null=True
            ),
        ),
        migrations.AddField(
            model_name="extractionwater",
            name="pumpEmmissionFactor_kg_CO2_kWh",
            field=models.FloatField(
                help_text="Pump emission factor in kilograms of CO2 per kilowatt-hour",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opex",
            name="OPEX_recovered_EUR",
            field=models.FloatField(help_text="OPEX recovered in EUR", null=True),
        ),
        migrations.AddField(
            model_name="opex",
            name="OPEX_recovered_PCT",
            field=models.FloatField(help_text="OPEX recovered in percent", null=True),
        ),
        migrations.AddField(
            model_name="opex",
            name="last_updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userslocation",
            name="populationServed",
            field=models.IntegerField(
                help_text="Population served in the neighborhood", null=True
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="pumpEmissionRate_kg_CO2_h",
            field=models.FloatField(
                help_text="Pump emission rate in kilograms of CO2 per hour", null=True
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="source",
            field=models.ForeignKey(
                help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.availablefreshwater",
            ),
        ),
        migrations.CreateModel(
            name="TotalWaterProduction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "productionDay",
                    models.FloatField(help_text="in Million cubic meters per day"),
                ),
                (
                    "productionYR",
                    models.FloatField(
                        help_text="in Million cubic meters per year", null=True
                    ),
                ),
                ("costDay", models.FloatField(help_text="in EUR per day", null=True)),
                ("costYR", models.FloatField(help_text="in EUR per year", null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="watersupply.availablefreshwater",
                    ),
                ),
            ],
        ),
    ]
