# Generated by Django 5.2.7 on 2026-02-04 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_alter_city_area_km2_alter_city_currentpopulation_and_more"),
        ("watersupply", "0007_extractionwater_pumpemission_day_kg_co2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="availablefreshwater",
            name="region",
            field=models.ForeignKey(
                help_text="Region code from common.Region. Get automatically assigned on save.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.region",
            ),
        ),
        migrations.AlterField(
            model_name="extractionwater",
            name="source",
            field=models.ForeignKey(
                help_text="AvailableFreshWater ID from watersupply.AvailableFreshWater. Get automatically assigned on save.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="watersupply.availablefreshwater",
            ),
        ),
    ]
