# Generated by Django 5.2.7 on 2026-02-05 16:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_city_urbanizationrate_alter_city_geom_and_more'),
        ('watersupply', '0008_availablefreshwater_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteredresidential',
            old_name='user',
            new_name='userLocation',
        ),
        migrations.RemoveField(
            model_name='coveragewatersupply',
            name='Neighborhood',
        ),
        migrations.AddField(
            model_name='coveragewatersupply',
            name='city',
            field=models.ForeignKey(help_text='City code from common.City', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.city'),
        ),
        migrations.AlterField(
            model_name='areaaffecteddrought',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name='availablefreshwater',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
        ),
        migrations.AlterField(
            model_name='extractionwater',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
        ),
        migrations.AlterField(
            model_name='pipenetwork',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(srid=28992),
        ),
        migrations.AlterField(
            model_name='watertreatment',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=28992),
        ),
    ]
