# Generated by Django 5.2.12 on 2026-09-15 12:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DigitalElevationModelWMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#272727", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Digital Elevation Model WMS Layer",
                "verbose_name_plural": "Digital Elevation Model WMS Layers",
            },
        ),
        migrations.CreateModel(
            name="DigitalSurfaceModelWMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#4a90d9", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Digital Surface Model WMS Layer",
                "verbose_name_plural": "Digital Surface Model WMS Layers",
            },
        ),
        migrations.CreateModel(
            name="EnvironmentalCosts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("price_EUR_kg_CO2", models.FloatField()),
                ("price_EUR_price_EUR_droughtDamage_m3", models.FloatField()),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandCoverClasses",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "class_name",
                    models.CharField(
                        help_text="Name of the land cover class (e.g., 'Urban', 'Forest', 'Agriculture', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the land cover class"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandCoverWMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#4a90d9", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Land Cover WMS Layer",
                "verbose_name_plural": "Land Cover WMS Layers",
            },
        ),
        migrations.CreateModel(
            name="SurfaceMaterialProperties",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "material_name",
                    models.CharField(
                        help_text="Name of the material (e.g., 'Concrete', 'Asphalt', 'Grass', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "albedo",
                    models.FloatField(
                        help_text="Albedo value (0-1) representing the reflectivity of the material"
                    ),
                ),
                (
                    "thermal_conductivity",
                    models.FloatField(help_text="Thermal conductivity in W/(m*K)"),
                ),
                (
                    "specific_heat_capacity",
                    models.FloatField(help_text="Specific heat capacity in J/(kg*K)"),
                ),
                ("density", models.FloatField(help_text="Density in kg/m3")),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Surface Material Properties",
                "verbose_name_plural": "Surface Material Properties",
            },
        ),
        migrations.CreateModel(
            name="WallMaterialProperties",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "material_name",
                    models.CharField(
                        help_text="Name of the wall material (e.g., 'Brick', 'Wood', 'Insulated Panel', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "thermal_conductivity",
                    models.FloatField(help_text="Thermal conductivity in W/(m*K)"),
                ),
                (
                    "specific_heat_capacity",
                    models.FloatField(help_text="Specific heat capacity in J/(kg*K)"),
                ),
                ("density", models.FloatField(help_text="Density in kg/m3")),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Wall Material Properties",
                "verbose_name_plural": "Wall Material Properties",
            },
        ),
        migrations.CreateModel(
            name="DigitalElevationModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Acquisition/generation date of the elevation model",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data provider of the raster (e.g., 'AHN4 (PDOK)')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the raster in meters",
                        null=True,
                    ),
                ),
                (
                    "dem_raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing elevation values",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DigitalSurfaceModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Acquisition/generation date of the surface model",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data provider of the raster (e.g., 'AHN4 (PDOK)')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the raster in meters",
                        null=True,
                    ),
                ),
                (
                    "dsm_raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing surface elevation values",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandCoverRaster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Acquisition/generation date of the raster",
                        null=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data provider of the raster (e.g., 'PDOK', 'Sentinel-2', 'Google Earth Engine')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        blank=True,
                        help_text="Dataset or index represented by the raster (e.g., 'LGN2021', 'WORLDCOVER_2021_MAP', 'NDVI', 'lossyear')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the raster in meters",
                        null=True,
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing land cover classification values",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SatelliteImagery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Acquisition date/time of the satellite imagery",
                        null=True,
                    ),
                ),
                (
                    "satellite_type",
                    models.CharField(
                        blank=True,
                        help_text="Satellite or sensor that captured the imagery (e.g., 'Sentinel-2', 'Landsat', 'MODIS', etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "index",
                    models.CharField(
                        blank=True,
                        help_text="Type of satellite imagery index/product (e.g., 'TrueColor', 'NDVI', 'EVI', 'NDWI', etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the imagery in meters",
                        null=True,
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Raster file containing satellite imagery",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LandCoverVector",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "land_use",
                    models.CharField(
                        help_text="Land use type (e.g., 'Residential', 'Commercial', 'Industrial', 'Park', etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "percentage",
                    models.FloatField(
                        help_text="Percentage of the City covered by this land cover type"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
                (
                    "land_cover_type",
                    models.ForeignKey(
                        help_text="Type of land cover (e.g., 'Urban', 'Forest', 'Agriculture', etc.)",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="physicalEnv.landcoverclasses",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        help_text="Material properties of the land cover type, where known",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="physicalEnv.surfacematerialproperties",
                    ),
                ),
            ],
        ),
    ]
