# Generated by Django 5.2.12 on 2026-10-08 08:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physicalEnv", "0003_hilucslanduse"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilType",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        help_text="Soil code of the soil map, e.g. 'Hn21'",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Soil name of the soil map, e.g. 'Veldpodzolgronden; leemarm en zwak lemig fijn zand'",
                        max_length=200,
                    ),
                ),
                (
                    "soilGroup",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A: sand, gravel (low runoff)"),
                            ("B", "B: loam, silt loam (moderate runoff)"),
                            ("C", "C: clay loam (moderately high runoff)"),
                            ("D", "D: clay, peat (high runoff)"),
                        ],
                        help_text="Hydrologic soil group (SCS), derived from the soil name's texture",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "infiltrationMin_mm_h",
                    models.FloatField(
                        blank=True,
                        help_text="Lower bound of the final infiltration rate of the soil group, mm/h",
                        null=True,
                    ),
                ),
                (
                    "infiltrationMax_mm_h",
                    models.FloatField(
                        blank=True,
                        help_text="Upper bound of the final infiltration rate of the soil group, mm/h (empty for group A: no upper bound)",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Type",
                "verbose_name_plural": "Soil Types",
                "ordering": ["code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code", "name"), name="unique_soil_code_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SoilArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "mapAreaID",
                    models.CharField(
                        help_text="maparea_id of the soil map, e.g. 'V2025-1..soilarea.0000016921'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "soil_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="areas",
                        to="physicalEnv.soiltype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Soil Area",
                "verbose_name_plural": "Soil Areas",
            },
        ),
    ]
