# Generated by Django 5.2.12 on 2026-10-08 09:36

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0004_district_urban_area_neighborhood_urban_area_and_more"),
        ("physicalEnv", "0004_soiltype_soilarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundwaterDepth",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "statistic",
                    models.CharField(
                        choices=[
                            ("GHG", "GHG: mean highest groundwater level"),
                            ("GLG", "GLG: mean lowest groundwater level"),
                            ("GVG", "GVG: mean spring groundwater level"),
                        ],
                        help_text="Which groundwater level statistic the raster holds",
                        max_length=3,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Data provider of the raster (e.g., 'BIS Nederland')",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resolution",
                    models.FloatField(
                        blank=True,
                        help_text="Spatial resolution of the raster in meters",
                        null=True,
                    ),
                ),
                (
                    "depth_raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Groundwater depth in cm below ground level (254 = 254 cm or deeper, 255 = nodata)",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "cog_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to the exported Cloud-Optimized GeoTIFF served by TiTiler",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Groundwater Depth",
                "verbose_name_plural": "Groundwater Depths",
            },
        ),
    ]
