# Generated by Django 5.2.12 on 2026-10-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("physicalEnv", "0005_groundwaterdepth"),
    ]

    operations = [
        migrations.AddField(
            model_name="soiltype",
            name="unitCode",
            field=models.CharField(
                blank=True,
                help_text="Main soil unit of the map legend (first_soilcode), e.g. 'Hn21' for 'Hn21/Hd21'; colours the soil map (mainMap/styles/soilStyles.py)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="soiltype",
            name="unitName",
            field=models.CharField(
                blank=True,
                help_text="Legend name of the main soil unit (first_soilname)",
                max_length=200,
                null=True,
            ),
        ),
    ]
