# Generated by Django 5.2.7 on 2026-02-06 12:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandSurfaceTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Land Surface Temperature values in degrees Celsius.', null=True, srid=28992, verbose_name='LST Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MeanRadiantTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Mean Radiant Temperature values in degrees Celsius.', null=True, srid=28992, verbose_name='Tmrt Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Mean Radiant Temperature',
                'verbose_name_plural': 'Mean Radiant Temperatures',
            },
        ),
        migrations.CreateModel(
            name='NatureBasedSolutionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the nature-based solution (e.g., 'Green Roof', 'Urban Tree Canopy', etc.)", max_length=200, verbose_name='NBS Name')),
                ('description', models.TextField(help_text='Detailed description of the nature-based solution and its benefits for urban heat mitigation.', verbose_name='NBS Description')),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text="Location of the nature-based solution (e.g., 'Green Roof', 'Urban Tree Canopy', etc.)", srid=28992, verbose_name='NBS Geometry')),
                ('image', models.ImageField(blank=True, help_text='Optional image illustrating the nature-based solution.', null=True, upload_to='nbs_images/', verbose_name='NBS Image')),
            ],
            options={
                'verbose_name': 'Nature-Based Solution Point',
                'verbose_name_plural': 'Nature-Based Solution Points',
            },
        ),
        migrations.CreateModel(
            name='NatureBasedSolutionPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the nature-based solution (e.g., 'Green Roof', 'Urban Tree Canopy', etc.)", max_length=200, verbose_name='NBS Name')),
                ('description', models.TextField(help_text='Detailed description of the nature-based solution and its benefits for urban heat mitigation.', verbose_name='NBS Description')),
                ('area', models.FloatField(help_text='Area of the nature-based solution in square meters.', verbose_name='NBS Area')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(help_text="Geometry of the nature-based solution (e.g., 'Green Roof', 'Urban Tree Canopy', etc.)", srid=28992, verbose_name='NBS Geometry')),
                ('image', models.ImageField(blank=True, help_text='Optional image illustrating the nature-based solution.', null=True, upload_to='nbs_images/', verbose_name='NBS Image')),
            ],
            options={
                'verbose_name': 'Nature-Based Solution Polygon',
                'verbose_name_plural': 'Nature-Based Solution Polygons',
            },
        ),
        migrations.CreateModel(
            name='SkyViewFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Sky View Factor values (0 to 1).', null=True, srid=28992, verbose_name='SVF Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Sky View Factor',
                'verbose_name_plural': 'Sky View Factor',
            },
        ),
        migrations.CreateModel(
            name='StressCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, help_text="Thermal stress category (e.g., 'No Thermal Stress', 'Moderate Heat Stress', etc.)", max_length=50, null=True, verbose_name='Stress Category')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the thermal stress category.', null=True, verbose_name='Category Description')),
            ],
            options={
                'verbose_name': 'Stress Category',
                'verbose_name_plural': 'Stress Categories',
            },
        ),
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Base WMS endpoint URL', max_length=500)),
                ('layers_param', models.CharField(help_text='WMS layers parameter', max_length=200)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('legend_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opacity', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WMS Layer',
                'verbose_name_plural': 'WMS Layers',
            },
        ),
        migrations.CreateModel(
            name='PET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Physiological Equivalent Temperature values in degrees Celsius.', null=True, srid=28992, verbose_name='PET Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, help_text="Thermal comfort category based on PET values (e.g., 'Cold Stress', 'Comfortable', 'Heat Stress', etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='urbanHeat.stresscategory', verbose_name='PET Category')),
            ],
            options={
                'verbose_name': 'Physiological Equivalent Temperature',
                'verbose_name_plural': 'Physiological Equivalent Temperature',
            },
        ),
        migrations.CreateModel(
            name='SurfaceUrbanHeatIslandIntensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Surface Urban Heat Island Intensity values in degrees Celsius.', null=True, srid=28992, verbose_name='SUHII Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, help_text="Thermal stress category based on SUHII values (e.g., 'No Heat Island Effect', 'Moderate Heat Island Effect', etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='urbanHeat.stresscategory', verbose_name='SUHII Category')),
            ],
            options={
                'verbose_name': 'Surface Urban Heat Island Intensity',
                'verbose_name_plural': 'Surface Urban Heat Island Intensities',
            },
        ),
        migrations.CreateModel(
            name='UTCI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Raster file containing Universal Thermal Climate Index values in degrees Celsius.', null=True, srid=28992, verbose_name='UTCI Raster')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, help_text="Thermal stress category based on UTCI values (e.g., 'No Thermal Stress', 'Moderate Heat Stress', etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, to='urbanHeat.stresscategory', verbose_name='UTCI Category')),
            ],
            options={
                'verbose_name': 'Universal Thermal Climate Index',
                'verbose_name_plural': 'Universal Thermal Climate Index Measurements',
            },
        ),
    ]
