# Generated by Django 5.2.7 on 2026-02-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("urbanHeat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meanradianttemperature",
            options={
                "verbose_name": "Mean Radiant Temperature",
                "verbose_name_plural": "Mean Radiant Temperature",
            },
        ),
        migrations.AlterModelOptions(
            name="surfaceurbanheatislandintensity",
            options={
                "verbose_name": "Surface Urban Heat Island Intensity",
                "verbose_name_plural": "Surface Urban Heat Island Intensity",
            },
        ),
    ]
