# Generated by Django 5.2.12 on 2026-09-15 12:47

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of forest (e.g., deciduous, coniferous, mixed, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Forest",
                "verbose_name_plural": "Forests",
            },
        ),
        migrations.CreateModel(
            name="ProtectedArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "inspireID",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the protected area from INSPIRE dataset",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "protection_type",
                    models.CharField(
                        choices=[
                            ("N2K", "Natura 2000"),
                            ("NNN", "Natuurnetwerk Nederland"),
                            ("RAM", "Ramsar"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Protected Area",
                "verbose_name_plural": "Protected Areas",
            },
        ),
        migrations.CreateModel(
            name="WaterBodies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "localId",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the water body from PDOK dataset",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of water body (e.g., lake, reservoir, stream, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "persistance",
                    models.CharField(
                        blank=True,
                        help_text="Persistence of the water body (e.g., permanent, temporary, seasonal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Body",
                "verbose_name_plural": "Water Bodies",
            },
        ),
        migrations.CreateModel(
            name="WaterWaysLN",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of waterway (e.g., river, canal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lowerWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Lower width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "upperWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Upper width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "persistence",
                    models.CharField(
                        blank=True,
                        help_text="Persistence of the waterway (e.g., permanent, temporary, seasonal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "localId",
                    models.CharField(
                        help_text="Unique identifier for the waterway from PDOK dataset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Way",
                "verbose_name_plural": "Water Ways",
            },
        ),
        migrations.CreateModel(
            name="WaterWaysPG",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "localId",
                    models.CharField(
                        help_text="Unique identifier for the waterway from PDOK dataset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "lowerWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Lower width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "upperWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Upper width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "persistence",
                    models.CharField(
                        blank=True,
                        help_text="Persistence of the waterway (e.g., permanent, temporary, seasonal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Way Polygon",
                "verbose_name_plural": "Water Ways Polygons",
            },
        ),
        migrations.CreateModel(
            name="GreenSpaces",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of green space (e.g., park, garden, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "area",
                    models.FloatField(
                        blank=True,
                        help_text="Area of the green space in square meters",
                        null=True,
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        blank=True,
                        help_text="City this green space belongs to (resolved via centroid intersection)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Green Space",
                "verbose_name_plural": "Green Spaces",
            },
        ),
    ]
