# Generated by Django 5.2.12 on 2026-03-10 15:04

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Forests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Forest",
                "verbose_name_plural": "Forests",
            },
        ),
        migrations.CreateModel(
            name="ProtectedArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "protection_type",
                    models.CharField(
                        choices=[
                            ("N2K", "Natura 2000"),
                            ("NNN", "Natuurnetwerk Nederland"),
                            ("RAM", "Ramsar"),
                            ("OTH", "Other"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Protected Area",
                "verbose_name_plural": "Protected Areas",
            },
        ),
        migrations.CreateModel(
            name="WaterBodies",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Body",
                "verbose_name_plural": "Water Bodies",
            },
        ),
        migrations.CreateModel(
            name="WaterWays",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Way",
                "verbose_name_plural": "Water Ways",
            },
        ),
    ]
