# Generated by Django 5.2.12 on 2026-10-06 13:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrative", "0004_district_urban_area_neighborhood_urban_area_and_more"),
        ("nature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tree",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sourceID",
                    models.CharField(
                        blank=True,
                        help_text="Identifier in the source dataset, e.g. 'osm:node/123' for OpenStreetMap",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        blank=True,
                        help_text="Scientific species name (e.g., Tilia x europaea)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "genus",
                    models.CharField(
                        blank=True,
                        help_text="Scientific genus (e.g., Tilia)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "leafType",
                    models.CharField(
                        blank=True,
                        help_text="broadleaved, needleleaved, ...",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "leafCycle",
                    models.CharField(
                        blank=True,
                        help_text="deciduous, evergreen, ...",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "height_m",
                    models.FloatField(
                        blank=True, help_text="Tree height in meters", null=True
                    ),
                ),
                (
                    "circumference_m",
                    models.FloatField(
                        blank=True,
                        help_text="Trunk circumference at breast height in meters",
                        null=True,
                    ),
                ),
                (
                    "crownDiameter_m",
                    models.FloatField(
                        blank=True, help_text="Crown diameter in meters", null=True
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=28992)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        help_text="Neighborhood the tree stands in (resolved spatially on import)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tree",
                "verbose_name_plural": "Trees",
            },
        ),
    ]
