# Generated by Django 5.2.12 on 2026-05-26 11:00

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GreenSpaces",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "area",
                    models.FloatField(
                        blank=True,
                        help_text="Area of the green space in square meters",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Green Space",
                "verbose_name_plural": "Green Spaces",
            },
        ),
    ]
