# Generated by Django 5.2.12 on 2026-05-26 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_district_id_alter_neighborhood_id"),
        ("nature", "0002_greenspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="greenspaces",
            name="city",
            field=models.ForeignKey(
                blank=True,
                help_text="City this green space belongs to (resolved via centroid intersection)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
            ),
        ),
    ]
