# Generated by Django 5.2.12 on 2026-08-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0003_greenspaces_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="forests",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of forest (e.g., deciduous, coniferous, mixed, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="greenspaces",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of green space (e.g., park, garden, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="waterbodies",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of water body (e.g., lake, reservoir, stream, etc.)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="waterways",
            name="type",
            field=models.CharField(
                blank=True,
                help_text="Type of waterway (e.g., river, canal, etc.)",
                max_length=100,
                null=True,
            ),
        ),
    ]
