# Generated by Django 5.2.12 on 2026-09-07 11:56

import django.contrib.gis.db.models.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nature", "0004_forests_type_greenspaces_type_waterbodies_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterWaysLN",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        help_text="Type of waterway (e.g., river, canal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "lowerWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Lower width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "upperWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Upper width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "persistence",
                    models.CharField(
                        blank=True,
                        help_text="Persistence of the waterway (e.g., permanent, temporary, seasonal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "localId",
                    models.CharField(
                        help_text="Unique identifier for the waterway from PDOK dataset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Way",
                "verbose_name_plural": "Water Ways",
            },
        ),
        migrations.CreateModel(
            name="WaterWaysPG",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "localId",
                    models.CharField(
                        help_text="Unique identifier for the waterway from PDOK dataset",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "lowerWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Lower width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "upperWidth",
                    models.FloatField(
                        blank=True,
                        help_text="Upper width of the waterway in meters",
                        null=True,
                    ),
                ),
                (
                    "persistence",
                    models.CharField(
                        blank=True,
                        help_text="Persistence of the waterway (e.g., permanent, temporary, seasonal, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PolygonField(srid=28992)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Water Way Polygon",
                "verbose_name_plural": "Water Ways Polygons",
            },
        ),
        migrations.DeleteModel(
            name="WaterWays",
        ),
        migrations.AddField(
            model_name="protectedarea",
            name="inspireID",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the protected area from INSPIRE dataset",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="waterbodies",
            name="localId",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the water body from PDOK dataset",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="waterbodies",
            name="persistance",
            field=models.CharField(
                blank=True,
                help_text="Persistence of the water body (e.g., permanent, temporary, seasonal, etc.)",
                max_length=100,
                null=True,
            ),
        ),
    ]
