# Generated by Django 5.2.12 on 2026-03-04 10:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherStation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the weather station", max_length=200
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        help_text="Location of the weather station", srid=28992
                    ),
                ),
                (
                    "elevation_m",
                    models.FloatField(help_text="Elevation of the station in meters"),
                ),
                (
                    "installation_date",
                    models.DateField(help_text="Date when the station was installed"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the station is currently operational",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Station",
                "verbose_name_plural": "Weather Stations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WMSLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("display_name", models.CharField(max_length=200)),
                (
                    "url",
                    models.URLField(help_text="Base WMS endpoint URL", max_length=500),
                ),
                (
                    "layers_param",
                    models.CharField(help_text="WMS layers parameter", max_length=200),
                ),
                ("color", models.CharField(default="#4a90d9", max_length=7)),
                ("legend_url", models.URLField(blank=True, max_length=500, null=True)),
                ("opacity", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "WMS Layer",
                "verbose_name_plural": "WMS Layers",
            },
        ),
        migrations.CreateModel(
            name="TemperatureRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this layer", max_length=200
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of the weather data", null=True
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Interpolated raster data (stored in PostGIS)",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Bounding box of this raster",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "resolution_m",
                    models.FloatField(
                        default=10, help_text="Raster resolution in meters"
                    ),
                ),
                (
                    "interpolation_method",
                    models.CharField(
                        choices=[
                            ("idw", "Inverse Distance Weighting"),
                            ("kriging", "Kriging"),
                            ("spline", "Spline"),
                        ],
                        default="idw",
                        help_text="Spatial interpolation method used",
                        max_length=50,
                    ),
                ),
                ("cog_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Statistics and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Province",
                    models.ForeignKey(
                        blank=True,
                        help_text="Province this raster covers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.province",
                    ),
                ),
                (
                    "source_stations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Weather stations used for interpolation",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temperature Raster",
                "verbose_name_plural": "Temperature Rasters",
                "indexes": [
                    models.Index(fields=["date"], name="weather_tem_date_b54b35_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PrecipitationRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this layer", max_length=200
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of the weather data", null=True
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Interpolated raster data (stored in PostGIS)",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Bounding box of this raster",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "resolution_m",
                    models.FloatField(
                        default=10, help_text="Raster resolution in meters"
                    ),
                ),
                (
                    "interpolation_method",
                    models.CharField(
                        choices=[
                            ("idw", "Inverse Distance Weighting"),
                            ("kriging", "Kriging"),
                            ("spline", "Spline"),
                        ],
                        default="idw",
                        help_text="Spatial interpolation method used",
                        max_length=50,
                    ),
                ),
                ("cog_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Statistics and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Province",
                    models.ForeignKey(
                        blank=True,
                        help_text="Province this raster covers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.province",
                    ),
                ),
                (
                    "source_stations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Weather stations used for interpolation",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precipitation Raster",
                "verbose_name_plural": "Precipitation Rasters",
                "indexes": [
                    models.Index(fields=["date"], name="weather_pre_date_1003c4_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Meteorology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, help_text="Date and time of the weather data"
                    ),
                ),
                (
                    "precipitation_mm",
                    models.FloatField(
                        blank=True, help_text="Precipitation in millimeters", null=True
                    ),
                ),
                (
                    "wind_speed_m_s",
                    models.FloatField(
                        blank=True,
                        help_text="Wind speed in meters per second",
                        null=True,
                    ),
                ),
                (
                    "temperature_C",
                    models.FloatField(
                        blank=True,
                        help_text="Air temperature in degrees Celsius",
                        null=True,
                    ),
                ),
                (
                    "solar_radiation_W_m2",
                    models.FloatField(
                        blank=True,
                        help_text="Solar radiation in Watts per square meter",
                        null=True,
                    ),
                ),
                (
                    "humidity_percent",
                    models.FloatField(
                        blank=True,
                        help_text="Relative humidity in percentage",
                        null=True,
                    ),
                ),
                (
                    "vapor_pressure_hPa",
                    models.FloatField(
                        blank=True,
                        help_text="Vapor pressure in hectopascals",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Weather station that recorded this measurement",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurements",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weather Measurement",
                "verbose_name_plural": "Weather Measurements",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "station"], name="weather_met_date_ed8888_idx"
                    )
                ],
                "unique_together": {("station", "date")},
            },
        ),
        migrations.CreateModel(
            name="HumidityRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this layer", max_length=200
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of the weather data", null=True
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Interpolated raster data (stored in PostGIS)",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Bounding box of this raster",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "resolution_m",
                    models.FloatField(
                        default=10, help_text="Raster resolution in meters"
                    ),
                ),
                (
                    "interpolation_method",
                    models.CharField(
                        choices=[
                            ("idw", "Inverse Distance Weighting"),
                            ("kriging", "Kriging"),
                            ("spline", "Spline"),
                        ],
                        default="idw",
                        help_text="Spatial interpolation method used",
                        max_length=50,
                    ),
                ),
                ("cog_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Statistics and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Province",
                    models.ForeignKey(
                        blank=True,
                        help_text="Province this raster covers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.province",
                    ),
                ),
                (
                    "source_stations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Weather stations used for interpolation",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Humidity Raster",
                "verbose_name_plural": "Humidity Rasters",
                "indexes": [
                    models.Index(fields=["date"], name="weather_hum_date_b1780a_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="WindSpeedRaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this layer", max_length=200
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="Date of the weather data", null=True
                    ),
                ),
                (
                    "raster",
                    django.contrib.gis.db.models.fields.RasterField(
                        blank=True,
                        help_text="Interpolated raster data (stored in PostGIS)",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Bounding box of this raster",
                        null=True,
                        srid=28992,
                    ),
                ),
                (
                    "resolution_m",
                    models.FloatField(
                        default=10, help_text="Raster resolution in meters"
                    ),
                ),
                (
                    "interpolation_method",
                    models.CharField(
                        choices=[
                            ("idw", "Inverse Distance Weighting"),
                            ("kriging", "Kriging"),
                            ("spline", "Spline"),
                        ],
                        default="idw",
                        help_text="Spatial interpolation method used",
                        max_length=50,
                    ),
                ),
                ("cog_path", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Statistics and metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "Province",
                    models.ForeignKey(
                        blank=True,
                        help_text="Province this raster covers",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.province",
                    ),
                ),
                (
                    "source_stations",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Weather stations used for interpolation",
                        to="weather.weatherstation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wind Speed Raster",
                "verbose_name_plural": "Wind Speed Rasters",
                "indexes": [
                    models.Index(fields=["date"], name="weather_win_date_6335a3_idx")
                ],
            },
        ),
    ]
