# Generated by Django 5.2.7 on 2026-02-05 16:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0007_city_urbanizationrate_alter_city_geom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the weather station', max_length=200)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Location of the weather station', srid=28992)),
                ('elevation_m', models.FloatField(help_text='Elevation of the station in meters')),
                ('installation_date', models.DateField(help_text='Date when the station was installed')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the station is currently operational')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WMSLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='Base WMS endpoint URL', max_length=500)),
                ('layers_param', models.CharField(help_text='WMS layers parameter', max_length=200)),
                ('color', models.CharField(default='#4a90d9', max_length=7)),
                ('legend_url', models.URLField(blank=True, max_length=500, null=True)),
                ('opacity', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'WMS Layer',
                'verbose_name_plural': 'WMS Layers',
            },
        ),
        migrations.CreateModel(
            name='WeatherMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(db_index=True, help_text='Date and time of the weather data')),
                ('precipitation_mm', models.FloatField(blank=True, help_text='Precipitation in millimeters', null=True)),
                ('wind_speed_m_s', models.FloatField(blank=True, help_text='Wind speed in meters per second', null=True)),
                ('temperature_C', models.FloatField(blank=True, help_text='Air temperature in degrees Celsius', null=True)),
                ('solar_radiation_W_m2', models.FloatField(blank=True, help_text='Solar radiation in Watts per square meter', null=True)),
                ('humidity_percent', models.FloatField(blank=True, help_text='Relative humidity in percentage', null=True)),
                ('vapor_pressure_hPa', models.FloatField(blank=True, help_text='Vapor pressure in hectopascals', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(help_text='Weather station that recorded this measurement', on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='weather.weatherstation')),
            ],
            options={
                'ordering': ['-date_time'],
                'indexes': [models.Index(fields=['date_time', 'station'], name='weather_wea_date_ti_1469bc_idx')],
                'unique_together': {('station', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='TemperatureRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this layer', max_length=200)),
                ('date_time', models.DateTimeField(db_index=True, help_text='Date and time of the weather data')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Interpolated raster data (stored in PostGIS)', null=True, srid=28992)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounding box of this raster', null=True, srid=28992)),
                ('resolution_m', models.FloatField(default=10, help_text='Raster resolution in meters')),
                ('interpolation_method', models.CharField(choices=[('idw', 'Inverse Distance Weighting'), ('kriging', 'Kriging'), ('spline', 'Spline')], default='idw', help_text='Spatial interpolation method used', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Statistics and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text='Region this raster covers', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region')),
                ('source_stations', models.ManyToManyField(blank=True, help_text='Weather stations used for interpolation', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Temperature Raster',
                'verbose_name_plural': 'Temperature Rasters',
                'indexes': [models.Index(fields=['date_time'], name='weather_tem_date_ti_1e954d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrecipitationRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this layer', max_length=200)),
                ('date_time', models.DateTimeField(db_index=True, help_text='Date and time of the weather data')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Interpolated raster data (stored in PostGIS)', null=True, srid=28992)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounding box of this raster', null=True, srid=28992)),
                ('resolution_m', models.FloatField(default=10, help_text='Raster resolution in meters')),
                ('interpolation_method', models.CharField(choices=[('idw', 'Inverse Distance Weighting'), ('kriging', 'Kriging'), ('spline', 'Spline')], default='idw', help_text='Spatial interpolation method used', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Statistics and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text='Region this raster covers', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region')),
                ('source_stations', models.ManyToManyField(blank=True, help_text='Weather stations used for interpolation', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Precipitation Raster',
                'verbose_name_plural': 'Precipitation Rasters',
                'indexes': [models.Index(fields=['date_time'], name='weather_pre_date_ti_5d1b5c_idx')],
            },
        ),
        migrations.CreateModel(
            name='HumidityRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this layer', max_length=200)),
                ('date_time', models.DateTimeField(db_index=True, help_text='Date and time of the weather data')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Interpolated raster data (stored in PostGIS)', null=True, srid=28992)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounding box of this raster', null=True, srid=28992)),
                ('resolution_m', models.FloatField(default=10, help_text='Raster resolution in meters')),
                ('interpolation_method', models.CharField(choices=[('idw', 'Inverse Distance Weighting'), ('kriging', 'Kriging'), ('spline', 'Spline')], default='idw', help_text='Spatial interpolation method used', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Statistics and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text='Region this raster covers', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region')),
                ('source_stations', models.ManyToManyField(blank=True, help_text='Weather stations used for interpolation', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Humidity Raster',
                'verbose_name_plural': 'Humidity Rasters',
                'indexes': [models.Index(fields=['date_time'], name='weather_hum_date_ti_8b6ab9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WindSpeedRaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this layer', max_length=200)),
                ('date_time', models.DateTimeField(db_index=True, help_text='Date and time of the weather data')),
                ('raster', django.contrib.gis.db.models.fields.RasterField(blank=True, help_text='Interpolated raster data (stored in PostGIS)', null=True, srid=28992)),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Bounding box of this raster', null=True, srid=28992)),
                ('resolution_m', models.FloatField(default=10, help_text='Raster resolution in meters')),
                ('interpolation_method', models.CharField(choices=[('idw', 'Inverse Distance Weighting'), ('kriging', 'Kriging'), ('spline', 'Spline')], default='idw', help_text='Spatial interpolation method used', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Statistics and metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, help_text='Region this raster covers', null=True, on_delete=django.db.models.deletion.CASCADE, to='common.region')),
                ('source_stations', models.ManyToManyField(blank=True, help_text='Weather stations used for interpolation', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': 'Wind Speed Raster',
                'verbose_name_plural': 'Wind Speed Rasters',
                'indexes': [models.Index(fields=['date_time'], name='weather_win_date_ti_e16d5c_idx')],
            },
        ),
    ]
