# Generated by Django 5.2.12 on 2026-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmslayer",
            name="has_time_dimension",
            field=models.BooleanField(
                default=False,
                help_text="Whether this WMS layer exposes a WMS TIME dimension that should be animated on the map",
            ),
        ),
        migrations.AddField(
            model_name="wmslayer",
            name="time_frame_count",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Number of most-recent time steps to loop through when animated",
            ),
        ),
    ]
