# Generated by Django 5.2.7 on 2026-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meteorology",
            options={
                "ordering": ["-date_time"],
                "verbose_name": "Weather Measurement",
                "verbose_name_plural": "Weather Measurements",
            },
        ),
        migrations.AlterModelOptions(
            name="weatherstation",
            options={
                "ordering": ["name"],
                "verbose_name": "Weather Station",
                "verbose_name_plural": "Weather Stations",
            },
        ),
    ]
