# Generated by Django 5.2.7 on 2026-02-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_surfacematerialproperties_options_and_more"),
        ("weather", "0002_alter_meteorology_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="meteorology",
            options={
                "ordering": ["-date"],
                "verbose_name": "Weather Measurement",
                "verbose_name_plural": "Weather Measurements",
            },
        ),
        migrations.RemoveIndex(
            model_name="humidityraster",
            name="weather_hum_date_ti_8b6ab9_idx",
        ),
        migrations.RemoveIndex(
            model_name="meteorology",
            name="weather_met_date_ti_e16f7e_idx",
        ),
        migrations.RemoveIndex(
            model_name="precipitationraster",
            name="weather_pre_date_ti_5d1b5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="temperatureraster",
            name="weather_tem_date_ti_1e954d_idx",
        ),
        migrations.RemoveIndex(
            model_name="windspeedraster",
            name="weather_win_date_ti_e16d5c_idx",
        ),
        migrations.RenameField(
            model_name="meteorology",
            old_name="date_time",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="humidityraster",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="precipitationraster",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="temperatureraster",
            name="date_time",
        ),
        migrations.RemoveField(
            model_name="windspeedraster",
            name="date_time",
        ),
        migrations.AddField(
            model_name="humidityraster",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date of the weather data", null=True
            ),
        ),
        migrations.AddField(
            model_name="precipitationraster",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date of the weather data", null=True
            ),
        ),
        migrations.AddField(
            model_name="temperatureraster",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date of the weather data", null=True
            ),
        ),
        migrations.AddField(
            model_name="windspeedraster",
            name="date",
            field=models.DateField(
                db_index=True, help_text="Date of the weather data", null=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meteorology",
            unique_together={("station", "date")},
        ),
        migrations.AddIndex(
            model_name="humidityraster",
            index=models.Index(fields=["date"], name="weather_hum_date_b1780a_idx"),
        ),
        migrations.AddIndex(
            model_name="meteorology",
            index=models.Index(
                fields=["date", "station"], name="weather_met_date_ed8888_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="precipitationraster",
            index=models.Index(fields=["date"], name="weather_pre_date_1003c4_idx"),
        ),
        migrations.AddIndex(
            model_name="temperatureraster",
            index=models.Index(fields=["date"], name="weather_tem_date_b54b35_idx"),
        ),
        migrations.AddIndex(
            model_name="windspeedraster",
            index=models.Index(fields=["date"], name="weather_win_date_6335a3_idx"),
        ),
    ]
