# Generated by Django 5.2.12 on 2026-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0002_wmslayer_has_time_dimension_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmslayer",
            name="time_refresh_minutes",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="How often (in minutes) this WMS republishes new data — the map re-polls the TIME dimension on this cadence to pick up new frames",
            ),
        ),
    ]
