# Generated by Django 5.2.12 on 2026-09-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_wmslayer_time_refresh_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="wmslayer",
            name="api_key_setting",
            field=models.CharField(
                blank=True,
                help_text="Name of a Django setting (e.g. KNMI_API_KEY) holding an API key to send as this WMS's Authorization header — for an authenticated-tier endpoint with a higher rate limit. Leave blank for anonymous access. When set, GetMap tile requests are routed through a server-side proxy so the key is never exposed to the browser.",
                max_length=100,
                null=True,
            ),
        ),
    ]
