# Generated by Django 5.2.7 on 2026-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0003_alter_meteorology_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="humidityraster",
            name="cog_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="precipitationraster",
            name="cog_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="temperatureraster",
            name="cog_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="windspeedraster",
            name="cog_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
