# Generated by Django 5.2.12 on 2026-03-04 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyEfficiencyLabels",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "label",
                    models.CharField(
                        choices=[
                            ("A+++", "A+++"),
                            ("A++", "A++"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        help_text="Energy efficiency label (e.g., A++, A+, B, C, etc.)",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of the energy efficiency label."
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy Label",
                "verbose_name_plural": "Energy Labels",
            },
        ),
        migrations.CreateModel(
            name="ElectricityCost",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                (
                    "cost_EUR_kWh",
                    models.FloatField(help_text="Cost in EUR per kilowatt-hour"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Province code from common.Province",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "Electricity Cost",
                "verbose_name_plural": "Electricity Costs",
            },
        ),
    ]
