# Generated by Django 5.2.7 on 2026-02-06 12:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Energy', '0001_initial'),
        ('common', '0001_initial'),  
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the facility', max_length=100)),
                ('type', models.CharField(choices=[('school', 'School'), ('hospital', 'Hospital'), ('fire_station', 'Fire Station'), ('police_station', 'Police Station'), ('market', 'Market'), ('transportNode', 'Transport Node')], help_text='Type of facility', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28992)),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the park', max_length=100)),
                ('area', models.FloatField(help_text='Area of the park in square meters')),
                ('vegetationType', models.CharField(help_text='Type of vegetation in the park (e.g., grass, trees, shrubs)', max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
            ],
            options={
                'verbose_name': 'Park',
                'verbose_name_plural': 'Parks',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name or identifier of the building', max_length=100)),
                ('address', models.CharField(help_text='Address of the building', max_length=200)),
                ('buildingType', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], help_text='Type of building (e.g., residential, commercial, industrial)', max_length=100)),
                ('height', models.FloatField(help_text='Height of the building in meters')),
                ('area', models.FloatField(help_text='Footprint area of the building in square meters')),
                ('constructionYear', models.IntegerField(blank=True, help_text='Year the building was constructed', null=True)),
                ('numberFloors', models.IntegerField(blank=True, help_text='Number of floors in the building', null=True)),
                ('numberUnits', models.IntegerField(blank=True, help_text='Number of housing or commercial units in the building', null=True)),
                ('vacant', models.BooleanField(default=False, help_text='Is the building vacant?')),
                ('vacancyRate', models.FloatField(blank=True, help_text='Vacancy rate in percentage (%)', null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('energyLabel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Energy.energyefficiencylabels', verbose_name='Energy Label')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.neighborhood', verbose_name='Neighborhood')),
                ('roofMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.SurfaceMaterialProperties', verbose_name='Roof Material')),
                ('wallMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.wallmaterialproperties', verbose_name='Wall Material')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the property', max_length=100)),
                ('grossArea', models.FloatField(help_text='Area of the property in square meters')),
                ('livingArea', models.FloatField(help_text='Living area of the property in square meters')),
                ('greenVisibility', models.FloatField(help_text='Green visibility index of the property')),
                ('bedrooms', models.IntegerField(help_text='Number of bedrooms in the property')),
                ('bathrooms', models.IntegerField(help_text='Number of bathrooms in the property')),
                ('connectivity', models.FloatField(help_text='Connectivity index of the property')),
                ('listingPrice_EUR', models.FloatField(help_text='Listing price of the property in EUR')),
                ('salePrice_EUR', models.FloatField(help_text='Sale price of the property in EUR')),
                ('unitaryPrice_EUR_per_sqm', models.FloatField(help_text='Unitary price in EUR per square meter')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=28992)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builtup.building', verbose_name='Building')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the street', max_length=100)),
                ('classification', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('residential', 'Residential')], help_text='Street classification (e.g., primary, secondary, residential)', max_length=50)),
                ('width', models.FloatField(help_text='Width of the street in meters')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=28992)),
                ('surfaceMaterial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.surfacematerialproperties', verbose_name='Surface Material')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
            },
        ),
        migrations.CreateModel(
            name='ZoningArea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zone_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('mixed', 'Mixed Use')], help_text='Type of zoning area', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the zoning area', null=True)),
                ('area', models.FloatField(help_text='Area of the zoning area in square meters')),
                ('benchmarkPrice_per_sqm', models.FloatField(blank=True, help_text='Benchmark price per square meter in EUR', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.neighborhood', verbose_name='Neighborhood')),
            ],
            options={
                'verbose_name': 'Zoning Area',
                'verbose_name_plural': 'Zoning Areas',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='ZoningArea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='builtup.zoningarea', verbose_name='Zoning Area'),
        ),
    ]
