# Generated by Django 5.2.12 on 2026-09-15 12:47

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("administrative", "0001_initial"),
        ("physicalEnv", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the facility", max_length=100),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("school", "School"),
                            ("hospital", "Hospital"),
                            ("fire_station", "Fire Station"),
                            ("police_station", "Police Station"),
                            ("market", "Market"),
                            ("transportNode", "Transport Node"),
                        ],
                        help_text="Type of facility",
                        max_length=100,
                    ),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=28992)),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        help_text="Unique identifier for the building (e.g., BAG ID)",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name or identifier of the building",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Address of the building",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "numberUnits",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of housing or commercial units in the building",
                        null=True,
                    ),
                ),
                (
                    "usageFunction",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("Residential function", "Residential function"),
                                ("Meeting function", "Meeting function"),
                                ("Cell function", "Cell function"),
                                ("Healthcare function", "Healthcare function"),
                                ("Industrial function", "Industrial function"),
                                ("Office function", "Office function"),
                                ("Lodging function", "Lodging function"),
                                ("Education function", "Education function"),
                                ("Sport function", "Sport function"),
                                ("Shop function", "Shop function"),
                                ("Other usage function", "Other usage function"),
                                ("Undefined", "Undefined"),
                            ],
                            max_length=100,
                        ),
                        blank=True,
                        default=list,
                        help_text="BAG gebruiksdoel (usage function(s)) of the building, where known, stored as human-readable labels; a Pand can have more than one, or 'Undefined' when BAG reports no usage function",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "buildingType",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("institutional", "Institutional"),
                            ("mixed", "Mixed Use"),
                        ],
                        help_text="Coarse building category, derived from usageFunction when set; use 'mixed' for buildings combining multiple usage functions (e.g. a Pand with several Verblijfsobjecten)",
                        max_length=100,
                    ),
                ),
                (
                    "energyLabel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+++", "A+++"),
                            ("A++", "A++"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        help_text="Dominant registered energy label for this building (RVO EP-Online register, via RIVM's rvo_energielabels WFS)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "energyLabelHighest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+++", "A+++"),
                            ("A++", "A++"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        help_text="Best registered label among this building's units (RVO EP-Online register, via RIVM's rvo_energielabels WFS)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "energyLabelLowest",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+++", "A+++"),
                            ("A++", "A++"),
                            ("A+", "A+"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("D", "D"),
                            ("E", "E"),
                            ("F", "F"),
                            ("G", "G"),
                        ],
                        help_text="Worst registered label among this building's units (RVO EP-Online register, via RIVM's rvo_energielabels WFS)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "energyLabelCount",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of registered energy labels found for this building (RVO EP-Online register, via RIVM's rvo_energielabels WFS)",
                        null=True,
                    ),
                ),
                (
                    "height_m",
                    models.FloatField(
                        blank=True,
                        help_text="Height of the building in meters",
                        null=True,
                    ),
                ),
                (
                    "area_sqm",
                    models.FloatField(
                        blank=True,
                        help_text="Footprint area of the building in square meters",
                        null=True,
                    ),
                ),
                (
                    "constructionYear",
                    models.IntegerField(
                        blank=True,
                        help_text="Year the building was constructed",
                        null=True,
                    ),
                ),
                (
                    "numberFloors",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of floors in the building",
                        null=True,
                    ),
                ),
                (
                    "vacant",
                    models.BooleanField(
                        default=False, help_text="Is the building vacant?"
                    ),
                ),
                (
                    "vacancyRate",
                    models.FloatField(
                        blank=True,
                        help_text="Vacancy rate in percentage (%)",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                        verbose_name="Neighborhood",
                    ),
                ),
                (
                    "roofMaterial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="physicalEnv.surfacematerialproperties",
                        verbose_name="Roof Material",
                    ),
                ),
                (
                    "wallMaterial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="physicalEnv.wallmaterialproperties",
                        verbose_name="Wall Material",
                    ),
                ),
                (
                    "connectivity",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Facilities the property is connected to",
                        to="builtup.facility",
                        verbose_name="Connections to Facilities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Building",
                "verbose_name_plural": "Buildings",
            },
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the park", max_length=100),
                ),
                (
                    "area",
                    models.FloatField(help_text="Area of the park in square meters"),
                ),
                (
                    "vegetationType",
                    models.CharField(
                        help_text="Type of vegetation in the park (e.g., grass, trees, shrubs)",
                        max_length=100,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        help_text="City code from administrative.City",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Park",
                "verbose_name_plural": "Parks",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(help_text="Name of the property", max_length=100),
                ),
                (
                    "houseNumber",
                    models.CharField(
                        blank=True,
                        help_text="House number of the property",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "grossArea",
                    models.FloatField(
                        help_text="Area of the property in square meters"
                    ),
                ),
                (
                    "livingArea",
                    models.FloatField(
                        blank=True,
                        help_text="Living area of the property in square meters",
                        null=True,
                    ),
                ),
                (
                    "greenVisibility",
                    models.FloatField(
                        blank=True,
                        help_text="Green visibility index of the property",
                        null=True,
                    ),
                ),
                (
                    "bedrooms",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of bedrooms in the property",
                        null=True,
                    ),
                ),
                (
                    "bathrooms",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of bathrooms in the property",
                        null=True,
                    ),
                ),
                (
                    "listingPrice_EUR",
                    models.FloatField(
                        blank=True,
                        help_text="Listing price of the property in EUR",
                        null=True,
                    ),
                ),
                (
                    "salePrice_EUR",
                    models.FloatField(
                        blank=True,
                        help_text="Sale price of the property in EUR",
                        null=True,
                    ),
                ),
                (
                    "unitaryPrice_EUR_per_sqm",
                    models.FloatField(
                        blank=True,
                        help_text="Unitary price in EUR per square meter",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("geom", django.contrib.gis.db.models.fields.PointField(srid=28992)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="builtup.building",
                        verbose_name="Building",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property",
                "verbose_name_plural": "Properties",
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "inspireID",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the street from INSPIRE dataset",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the street", max_length=100),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("residential", "Residential"),
                        ],
                        help_text="Street classification (e.g., primary, secondary, residential)",
                        max_length=50,
                    ),
                ),
                ("width", models.FloatField(help_text="Width of the street in meters")),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(srid=28992),
                ),
                (
                    "surfaceMaterial",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="physicalEnv.surfacematerialproperties",
                        verbose_name="Surface Material",
                    ),
                ),
            ],
            options={
                "verbose_name": "Street",
                "verbose_name_plural": "Streets",
            },
        ),
        migrations.CreateModel(
            name="ZoningArea",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "zone_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("industrial", "Industrial"),
                            ("mixed", "Mixed Use"),
                        ],
                        help_text="Type of zoning area, where known",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        blank=True,
                        help_text="Dutch legal plan instrument (e.g. 'bestemmingsplan'), where the zoning geometry comes from a legal spatial plan",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        blank=True,
                        help_text="Date the legal plan took effect, where known",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the zoning area",
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.FloatField(
                        help_text="Area of the zoning area in square meters"
                    ),
                ),
                (
                    "benchmarkPrice_per_sqm",
                    models.FloatField(
                        blank=True,
                        help_text="Benchmark price per square meter in EUR",
                        null=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="administrative.neighborhood",
                        verbose_name="Neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoning Area",
                "verbose_name_plural": "Zoning Areas",
            },
        ),
        migrations.AddField(
            model_name="building",
            name="ZoningArea",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="builtup.zoningarea",
                verbose_name="Zoning Area",
            ),
        ),
    ]
