# Generated by Django 5.2.12 on 2026-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="usageFunction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("woonfunctie", "Residential function"),
                    ("bijeenkomstfunctie", "Meeting function"),
                    ("celfunctie", "Cell function"),
                    ("gezondheidszorgfunctie", "Healthcare function"),
                    ("industriefunctie", "Industrial function"),
                    ("kantoorfunctie", "Office function"),
                    ("logiesfunctie", "Lodging function"),
                    ("onderwijsfunctie", "Education function"),
                    ("sportfunctie", "Sport function"),
                    ("winkelfunctie", "Shop function"),
                    ("overige gebruiksfunctie", "Other usage function"),
                ],
                help_text="BAG gebruiksdoel (usage function) of the building, where known",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="buildingType",
            field=models.CharField(
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("institutional", "Institutional"),
                    ("mixed", "Mixed Use"),
                ],
                help_text="Coarse building category, derived from usageFunction when set; use 'mixed' for buildings combining multiple usage functions (e.g. a Pand with several Verblijfsobjecten)",
                max_length=100,
            ),
        ),
    ]
