# Generated by Django 5.2.12 on 2026-10-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="postalCode",
            field=models.CharField(
                blank=True,
                help_text="Postal code of the property",
                max_length=10,
                null=True,
            ),
        ),
    ]
