# Generated by Django 5.2.7 on 2026-02-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name": "Facility", "verbose_name_plural": "Facilities"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "Property", "verbose_name_plural": "Properties"},
        ),
    ]
