# Generated by Django 5.2.7 on 2026-02-09 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0002_alter_facility_options_alter_property_options"),
        ("common", "0002_alter_surfacematerialproperties_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="area",
            new_name="area_sqm",
        ),
        migrations.RenameField(
            model_name="building",
            old_name="height",
            new_name="height_m",
        ),
        migrations.RemoveField(
            model_name="property",
            name="connectivity",
        ),
        migrations.AddField(
            model_name="building",
            name="connectivity",
            field=models.ManyToManyField(
                blank=True,
                help_text="Facilities the property is connected to",
                to="builtup.facility",
                verbose_name="Connections to Facilities",
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.neighborhood",
            ),
        ),
        migrations.AddField(
            model_name="park",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                help_text="City code from common.City",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.neighborhood",
            ),
        ),
    ]
