# Generated by Django 5.2.12 on 2026-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0002_building_usagefunction_alter_building_buildingtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
