# Generated by Django 5.2.12 on 2026-10-06 11:50

from django.db import migrations, models


# Columns in other apps that reference builtup_property.id. AlterField on the
# primary key leaves them as integer, so a Mortgage/Rental pointing at a
# BAG-numbered property would still overflow. Their model state is unchanged
# (a ForeignKey takes its type from the target), so this is SQL only.
REFERENCING_COLUMNS = [
    ("housing_mortgage", "property_id"),
    ("housing_rentals", "property_id"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0002_property_postalcode"),
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.RunSQL(
            sql=[f'ALTER TABLE "{t}" ALTER COLUMN "{c}" TYPE bigint' for t, c in REFERENCING_COLUMNS],
            reverse_sql=[f'ALTER TABLE "{t}" ALTER COLUMN "{c}" TYPE integer' for t, c in REFERENCING_COLUMNS],
        ),
    ]
