# Generated by Django 5.2.12 on 2026-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0003_property_bigint_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="sourceID",
            field=models.CharField(
                blank=True,
                help_text="Identifier in the source dataset, e.g. 'osm:node/123' for OpenStreetMap",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="subtype",
            field=models.CharField(
                blank=True,
                help_text="Finer source category within the type, e.g. OSM amenity 'kindergarten' or 'clinic'",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="park",
            name="sourceID",
            field=models.CharField(
                blank=True,
                help_text="Identifier in the source dataset, e.g. 'osm:way/123' for OpenStreetMap",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="park",
            name="vegetationType",
            field=models.CharField(
                blank=True,
                help_text="Type of vegetation in the park (e.g., grass, trees, shrubs), where known",
                max_length=100,
                null=True,
            ),
        ),
    ]
