# Generated by Django 5.2.12 on 2026-08-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0003_alter_building_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="height_m",
            field=models.FloatField(
                blank=True, help_text="Height of the building in meters", null=True
            ),
        ),
    ]
