# Generated by Django 5.2.12 on 2026-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0004_alter_building_height_m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="area_sqm",
            field=models.FloatField(
                blank=True,
                help_text="Footprint area of the building in square meters",
                null=True,
            ),
        ),
    ]
