# Generated by Django 5.2.12 on 2026-08-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0005_alter_building_area_sqm"),
        ("common", "0006_alter_city_cityname_alter_city_currentpopulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.neighborhood",
                verbose_name="Neighborhood",
            ),
        ),
    ]
