# Generated by Django 5.2.12 on 2026-09-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0006_alter_building_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="identifier",
            field=models.BigIntegerField(
                help_text="Unique identifier for the building (e.g., BAG ID)",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Name or identifier of the building",
                max_length=100,
                null=True,
            ),
        ),
    ]
