# Generated by Django 5.2.12 on 2026-09-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0007_building_identifier_alter_building_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Address of the building",
                max_length=200,
                null=True,
            ),
        ),
    ]
