# Generated by Django 5.2.12 on 2026-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0008_alter_building_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="identifier",
            field=models.BigIntegerField(
                help_text="Unique identifier for the building (e.g., BAG ID)", null=True
            ),
        ),
    ]
