# Generated by Django 5.2.12 on 2026-09-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0010_resync_building_id_sequence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="identifier",
        ),
        migrations.AlterField(
            model_name="building",
            name="id",
            field=models.BigIntegerField(
                help_text="Unique identifier for the building (e.g., BAG ID)",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
