# Generated by Django 5.2.12 on 2026-09-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0011_remove_building_identifier_alter_building_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="usageFunction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("woonfunctie", "Residential function"),
                    ("bijeenkomstfunctie", "Meeting function"),
                    ("celfunctie", "Cell function"),
                    ("gezondheidszorgfunctie", "Healthcare function"),
                    ("industriefunctie", "Industrial function"),
                    ("kantoorfunctie", "Office function"),
                    ("logiesfunctie", "Lodging function"),
                    ("onderwijsfunctie", "Education function"),
                    ("sportfunctie", "Sport function"),
                    ("winkelfunctie", "Shop function"),
                    ("overige gebruiksfunctie", "Other usage function"),
                ],
                help_text="BAG gebruiksdoel (usage function) of the building, where known",
                max_length=100,
                null=True,
            ),
        ),
    ]
