# Generated by Django 5.2.12 on 2026-09-02 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0014_alter_building_usagefunction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="usageFunction",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Residential function", "Residential function"),
                        ("Meeting function", "Meeting function"),
                        ("Cell function", "Cell function"),
                        ("Healthcare function", "Healthcare function"),
                        ("Industrial function", "Industrial function"),
                        ("Office function", "Office function"),
                        ("Lodging function", "Lodging function"),
                        ("Education function", "Education function"),
                        ("Sport function", "Sport function"),
                        ("Shop function", "Shop function"),
                        ("Other usage function", "Other usage function"),
                        ("Undefined", "Undefined"),
                    ],
                    max_length=100,
                ),
                blank=True,
                default=list,
                help_text="BAG gebruiksdoel (usage function(s)) of the building, where known, stored as human-readable labels; a Pand can have more than one, or 'Undefined' when BAG reports no usage function",
                null=True,
                size=None,
            ),
        ),
    ]
