# Generated by Django 5.2.12 on 2026-09-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0016_building_energy_label_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="street",
            name="inspireID",
            field=models.CharField(
                blank=True,
                help_text="Unique identifier for the street from INSPIRE dataset",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
