# Generated by Django 5.2.12 on 2026-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("builtup", "0017_street_inspireid"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="houseNumber",
            field=models.CharField(
                blank=True,
                help_text="House number of the property",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zoningarea",
            name="plan_type",
            field=models.CharField(
                blank=True,
                help_text="Dutch legal plan instrument (e.g. 'bestemmingsplan'), where the zoning geometry comes from a legal spatial plan",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zoningarea",
            name="valid_from",
            field=models.DateField(
                blank=True,
                help_text="Date the legal plan took effect, where known",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bathrooms",
            field=models.IntegerField(
                blank=True, help_text="Number of bathrooms in the property", null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="bedrooms",
            field=models.IntegerField(
                blank=True, help_text="Number of bedrooms in the property", null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="greenVisibility",
            field=models.FloatField(
                blank=True,
                help_text="Green visibility index of the property",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="listingPrice_EUR",
            field=models.FloatField(
                blank=True, help_text="Listing price of the property in EUR", null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="livingArea",
            field=models.FloatField(
                blank=True,
                help_text="Living area of the property in square meters",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="salePrice_EUR",
            field=models.FloatField(
                blank=True, help_text="Sale price of the property in EUR", null=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="unitaryPrice_EUR_per_sqm",
            field=models.FloatField(
                blank=True, help_text="Unitary price in EUR per square meter", null=True
            ),
        ),
        migrations.AlterField(
            model_name="zoningarea",
            name="zone_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("residential", "Residential"),
                    ("commercial", "Commercial"),
                    ("industrial", "Industrial"),
                    ("mixed", "Mixed Use"),
                ],
                help_text="Type of zoning area, where known",
                max_length=100,
                null=True,
            ),
        ),
    ]
