# Generated by Django 5.2.7 on 2026-02-06 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builtup', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralBankPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the policy data')),
                ('interest_rate', models.FloatField(help_text='Central bank interest rate in percentage (%)')),
                ('LTV_limit', models.FloatField(help_text='Loan-to-Value limit in percentage (%)')),
                ('LTI_limit', models.FloatField(help_text='Loan-to-Income limit in percentage (%)')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Central Bank Policy',
                'verbose_name_plural': 'Central Bank Policies',
            },
        ),
        migrations.CreateModel(
            name='CreditSupplyConditions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the credit supply conditions data')),
                ('mortgageRate', models.FloatField(help_text='Mortgage rate in percentage (%)')),
                ('mortgage_approval_rate', models.FloatField(help_text='Mortgage approval rate in percentage (%)')),
                ('average_down_payment', models.FloatField(help_text='Average down payment as a percentage of property value (%)')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Credit Supply Conditions',
                'verbose_name_plural': 'Credit Supply Conditions Records',
            },
        ),
        migrations.CreateModel(
            name='HousePriceIndex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the house price index data')),
                ('index_value', models.FloatField(help_text='Value of the house price index (base year = 100)')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.neighborhood', verbose_name='Neighborhood')),
            ],
            options={
                'verbose_name': 'House Price Index',
                'verbose_name_plural': 'House Price Index Records',
            },
        ),
        migrations.CreateModel(
            name='HousingAffordability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the housing affordability data')),
                ('medianIncome', models.FloatField(help_text='Median household income in EUR')),
                ('medianExpenditure', models.FloatField(help_text='Median household expenditure in EUR')),
                ('medianRent', models.FloatField(help_text='Median rent in EUR')),
                ('medianMortgage', models.FloatField(help_text='Median mortgage in EUR')),
                ('medianHousePrice', models.FloatField(help_text='Median house price in EUR')),
                ('medianDisposableIncome', models.FloatField(help_text='Median disposable income in EUR')),
                ('affordabilityIndex', models.FloatField(help_text='Affordability index (median house price divided by median income)')),
                ('affordabilityStressLevel', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], help_text='Affordability stress level (e.g., low, moderate, high)', max_length=50)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.neighborhood', verbose_name='Neighborhood')),
            ],
            options={
                'verbose_name': 'Housing Affordability',
                'verbose_name_plural': 'Housing Affordability Records',
            },
        ),
        migrations.CreateModel(
            name='HousingSupplyDemand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Year of the housing supply/demand data')),
                ('supply_units', models.IntegerField(help_text='Number of housing units supplied')),
                ('demand_units', models.IntegerField(help_text='Number of housing units demanded')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.neighborhood', verbose_name='Neighborhood')),
            ],
            options={
                'verbose_name': 'Housing Supply and Demand',
                'verbose_name_plural': 'Housing Supply and Demand Records',
            },
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalLoanAmount', models.FloatField(help_text='Total loan amount in EUR')),
                ('interestRate', models.FloatField(help_text='Mortgage interest rate in percentage (%)')),
                ('loanTermYears', models.IntegerField(help_text='Loan term in years')),
                ('downPayment', models.FloatField(help_text='Down payment in EUR')),
                ('monthlyPayment', models.FloatField(help_text='Monthly payment in EUR')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builtup.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Mortgage',
                'verbose_name_plural': 'Mortgages',
            },
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('monthlyRent', models.FloatField(help_text='Monthly rent in EUR')),
                ('annualRent', models.FloatField(help_text='Annual rent in EUR')),
                ('priceToRentRatio', models.FloatField(help_text='Price-to-rent ratio')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='builtup.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Rental',
                'verbose_name_plural': 'Rentals',
            },
        ),
    ]
