# Generated by Django 5.2.7 on 2026-02-09 15:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Housing", "0001_initial"),
        ("common", "0002_alter_surfacematerialproperties_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HousingProject",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "year",
                    models.IntegerField(help_text="Year of the housing project data"),
                ),
                (
                    "year_expected_completion",
                    models.IntegerField(
                        help_text="Year of expected completion of the housing project"
                    ),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="Name of the housing project", max_length=100
                    ),
                ),
                (
                    "project_description",
                    models.TextField(help_text="Description of the housing project"),
                ),
                (
                    "project_area",
                    models.FloatField(
                        help_text="Area of the housing project in square meters"
                    ),
                ),
                (
                    "project_units",
                    models.IntegerField(
                        help_text="Number of housing units in the project"
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=28992),
                ),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="common.neighborhood",
                        verbose_name="Neighborhood",
                    ),
                ),
            ],
            options={
                "verbose_name": "Housing Project",
                "verbose_name_plural": "Housing Projects",
            },
        ),
    ]
