# Generated by Django 5.2.12 on 2026-03-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_district_id_alter_neighborhood_id"),
        ("housing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="housingsupplydemand",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.city",
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="housingsupplydemand",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="common.neighborhood",
                verbose_name="Neighborhood",
            ),
        ),
    ]
